In [1]:
import pandas as pd
import numpy as np

In [2]:
import quandl

In [3]:
quandl.ApiConfig.api_key = "PCQqdJWPc-fYUJQ3JbGA"

### Import Analyst Rating History

In [4]:
rh = pd.read_csv("/Users/dunleavyjason/Documents/Metis/analyst_ratings/rh.csv")

In [5]:
rh.rename(columns = {"obs_date":"date"}, inplace=True)

In [6]:
rh["date"] = pd.to_datetime(rh["date"])

In [7]:
#drop unneeded columns
rh.drop(columns=["m_ticker", "comp_name", "comp_name_2", "exchange", "currency_code"], inplace=True)
rh

,ticker,date,rating_cnt_strong_buys,rating_cnt_mod_buys,rating_cnt_holds,rating_cnt_mod_sells,rating_cnt_strong_sells,rating_mean_recom,rating_cnt_with,rating_cnt_without
0,BHC,2019-01-01,7,1,2,0,2,2.0,12,0
1,CXO,2019-01-01,20,0,4,0,0,1.3,24,0
2,IBKC,2019-01-01,5,1,1,0,0,1.4,7,0
3,IDXX,2019-01-01,3,0,1,0,0,1.5,4,0
4,PAHC,2019-01-01,0,0,1,0,2,4.1,3,0
...,...,...,...,...,...,...,...,...,...,...
95405,WLL,2021-03-08,6,0,1,0,0,1.3,7,0
95406,WSM,2021-03-08,2,0,8,1,2,3.1,13,0
95407,XOM,2021-03-08,6,0,10,1,2,2.6,19,0
95408,XPEV,2021-03-08,4,0,2,0,0,1.7,6,0
95409,ZYXI,2021-03-08,3,0,3,0,0,2.0,6,0

In [8]:
#list of unique tickers
ticks = pd.DataFrame(rh.ticker.unique(), columns=["ticker"])
ticks

     ticker
0       BHC
1       CXO
2      IBKC
3      IDXX
4      PAHC
...     ...
6494   DBTX
6495    ELA
6496   NEXI
6497   THBR
6498   TLIS

[6499 rows x 1 columns]

### Import Core Fundamental Data

In [9]:
sf1 = pd.read_csv('/Users/dunleavyjason/Documents/Metis/core_fundamentals/sf1.csv')

In [10]:
sf1

,ticker,dimension,calendardate,datekey,reportperiod,lastupdated,accoci,assets,assetsavg,assetsc,...,sharesbas,shareswa,shareswadil,sps,tangibles,taxassets,taxexp,taxliabilities,tbvps,workingcapital
0,A,ARQ,2016-03-31,2016-06-07,2016-04-30,2021-03-02,-299000000.0,7.640000e+09,NaN,3.488000e+09,...,325521700.0,326000000.0,328000000.0,3.126,4.594000e+09,0.0,26000000.0,0.0,14.092,2.355000e+09
1,A,ARQ,2016-06-30,2016-09-07,2016-07-31,2021-03-02,-345000000.0,7.734000e+09,NaN,3.530000e+09,...,324384755.0,325000000.0,328000000.0,3.212,4.767000e+09,0.0,10000000.0,0.0,14.668,2.379000e+09
2,A,ARQ,2016-09-30,2016-12-20,2016-10-31,2021-03-02,-503000000.0,7.802000e+09,NaN,3.635000e+09,...,321747881.0,326000000.0,329000000.0,3.408,4.877000e+09,0.0,25000000.0,0.0,14.960,2.690000e+09
3,A,ARQ,2016-12-31,2017-03-08,2017-01-31,2021-03-02,-489000000.0,7.872000e+09,NaN,3.635000e+09,...,322300905.0,322000000.0,326000000.0,3.314,4.898000e+09,0.0,25000000.0,0.0,15.211,2.546000e+09
4,A,ARQ,2017-03-31,2017-06-06,2017-04-30,2021-03-02,-477000000.0,8.016000e+09,NaN,3.800000e+09,...,321337443.0,321000000.0,325000000.0,3.433,5.075000e+09,0.0,27000000.0,0.0,15.810,2.613000e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453981,FERG,MRY,2020-12-31,2020-07-31,2020-07-31,2021-03-09,0.0,1.345600e+04,12421.0,8.057000e+03,...,225048626.0,225048626.0,NaN,0.000,1.121400e+04,216.0,307.0,319.0,0.000,3.308000e+03
453982,ACQRU,ARQ,2020-12-31,2021-03-05,2020-12-31,2021-03-09,0.0,1.244970e+05,NaN,1.316200e+04,...,50000000.0,10000000.0,10000000.0,0.000,1.244970e+05,0.0,0.0,0.0,0.012,-1.022650e+05
453983,ACQRU,ART,2020-12-31,2021-03-05,2020-12-31,2021-03-09,0.0,1.244970e+05,NaN,1.316200e+04,...,50000000.0,10000000.0,NaN,NaN,1.244970e+05,0.0,NaN,0.0,0.012,-1.022650e+05
453984,ACQRU,MRQ,2020-12-31,2020-12-31,2020-12-31,2021-03-09,0.0,1.244970e+05,NaN,1.316200e+04,...,50000000.0,10000000.0,10000000.0,0.000,1.244970e+05,0.0,0.0,0.0,0.012,-1.022650e+05
453985,ACQRU,MRT,2020-12-31,2020-12-31,2020-12-31,2021-03-09,0.0,1.244970e+05,NaN,1.316200e+04,...,50000000.0,10000000.0,NaN,NaN,1.244970e+05,0.0,NaN,0.0,0.012,-1.022650e+05

In [11]:
tickers = pd.read_csv("/Users/dunleavyjason/Documents/Metis/core_fundamentals/tickers.csv")

In [12]:
#filter for tickers in SF1 table
sf1_tickers = tickers[tickers.table == "SF1"]
sf1_tickers

,table,permaticker,ticker,name,exchange,isdelisted,category,cusips,siccode,sicsector,...,currency,location,lastupdated,firstadded,firstpricedate,lastpricedate,firstquarter,lastquarter,secfilings,companysite
0,SF1,196290,A,Agilent Technologies Inc,NYSE,N,Domestic Common Stock,00846U101,3826.0,Manufacturing,...,USD,California; U.S.A,2021-03-02,2014-09-26,1999-11-18,2021-03-09,1997-06-30,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.agilent.com
1,SF1,124392,AA,Alcoa Corp,NYSE,N,Domestic Common Stock,013872106,3334.0,Manufacturing,...,USD,Pennsylvania; U.S.A,2021-02-25,2016-11-01,2016-11-01,2021-03-09,2014-12-31,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.alcoa.com
2,SF1,122827,AAAB,Admiralty Bancorp Inc,NASDAQ,Y,Domestic Common Stock,007231103,6022.0,Finance Insurance And Real Estate,...,USD,Florida; U.S.A,2019-07-29,2017-09-09,1998-09-25,2003-01-28,1997-09-30,2002-09-30,https://www.sec.gov/cgi-bin/browse-edgar?actio...,NaN
3,SF1,120538,AAAGY,Altana Aktiengesellschaft,NYSE,Y,ADR Common Stock,02143N103,2834.0,Manufacturing,...,EUR,Jordan,2019-05-17,2018-02-13,2002-05-22,2010-08-12,2000-12-31,2005-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,NaN
4,SF1,155760,AAAP,Advanced Accelerator Applications SA,NASDAQ,Y,ADR Common Stock,00790T100,2834.0,Manufacturing,...,EUR,France,2020-10-08,2016-05-19,2015-11-11,2018-02-09,2012-12-31,2017-09-30,https://www.sec.gov/cgi-bin/browse-edgar?actio...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15648,SF1,123153,ZYME,Zymeworks Inc,NYSE,N,Domestic Common Stock,98985W102,2834.0,Manufacturing,...,USD,British Columbia; Canada,2021-02-24,2017-09-02,2017-04-28,2021-03-09,2015-12-31,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.zymeworks.com
15649,SF1,157146,ZYNE,Zynerba Pharmaceuticals Inc,NASDAQ,N,Domestic Common Stock,98986X109,2834.0,Manufacturing,...,USD,Pennsylvania; U.S.A,2020-11-09,2016-04-15,2015-08-05,2021-03-09,2013-12-31,2020-09-30,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.zynerba.com
15650,SF1,188776,ZYTO,Zyto Corp,OTC,Y,Domestic Common Stock,989872106,3841.0,Manufacturing,...,USD,Utah; U.S.A,2020-10-19,2016-02-17,2008-01-30,2016-01-22,2008-12-31,2012-09-30,https://www.sec.gov/cgi-bin/browse-edgar?actio...,NaN
15651,SF1,198130,ZYXI,Zynex Inc,NASDAQ,N,Domestic Common Stock,98986M103,3845.0,Manufacturing,...,USD,Colorado; U.S.A,2021-02-26,2016-02-17,2004-02-25,2021-03-09,2008-03-31,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.zynex.com
15652,SF1,198673,ZZ,Sealy Corp,NYSE,Y,Domestic Common Stock,812139301,2510.0,Manufacturing,...,USD,Washington; U.S.A,2019-05-24,2015-06-09,2006-04-07,2013-03-15,2004-12-31,2012-03-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,NaN

In [13]:
fundamentals = pd.merge(sf1, sf1_tickers, on="ticker")

In [14]:
#filter for trailing 12-month data
fundamentals = fundamentals[fundamentals.dimension=="ART"]
fundamentals

,ticker,dimension,calendardate,datekey,reportperiod,lastupdated_x,accoci,assets,assetsavg,assetsc,...,currency,location,lastupdated_y,firstadded,firstpricedate,lastpricedate,firstquarter,lastquarter,secfilings,companysite
14,A,ART,2016-03-31,2016-06-07,2016-04-30,2021-03-02,-299000000.0,7.640000e+09,7.418000e+09,3.488000e+09,...,USD,California; U.S.A,2021-03-02,2014-09-26,1999-11-18,2021-03-09,1997-06-30,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.agilent.com
15,A,ART,2016-06-30,2016-09-07,2016-07-31,2021-03-02,-345000000.0,7.734000e+09,7.538750e+09,3.530000e+09,...,USD,California; U.S.A,2021-03-02,2014-09-26,1999-11-18,2021-03-09,1997-06-30,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.agilent.com
16,A,ART,2016-09-30,2016-12-20,2016-10-31,2021-03-02,-503000000.0,7.802000e+09,7.619500e+09,3.635000e+09,...,USD,California; U.S.A,2021-03-02,2014-09-26,1999-11-18,2021-03-09,1997-06-30,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.agilent.com
17,A,ART,2016-12-31,2017-03-08,2017-01-31,2021-03-02,-489000000.0,7.872000e+09,7.762000e+09,3.635000e+09,...,USD,California; U.S.A,2021-03-02,2014-09-26,1999-11-18,2021-03-09,1997-06-30,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.agilent.com
18,A,ART,2017-03-31,2017-06-06,2017-04-30,2021-03-02,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,...,USD,California; U.S.A,2021-03-02,2014-09-26,1999-11-18,2021-03-09,1997-06-30,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.agilent.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453686,PDOT.U,ART,2020-12-31,2021-03-01,2021-01-14,2021-03-09,0.0,5.361000e+04,NaN,NaN,...,USD,Texas; U.S.A,2021-03-09,2021-03-09,2021-03-09,2021-03-09,2020-12-31,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,NaN
453690,SVFB,ART,2020-12-31,2021-03-04,2020-12-31,2021-03-09,0.0,1.341800e+05,NaN,7.430000e+03,...,USD,California; U.S.A,2021-03-09,2021-03-09,2021-03-09,2021-03-09,2020-12-31,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,NaN
453694,SVFC,ART,2020-12-31,2021-03-04,2020-12-31,2021-03-09,0.0,1.329040e+05,NaN,6.154000e+03,...,USD,California; U.S.A,2021-03-09,2021-03-09,2021-03-09,2021-03-09,2020-12-31,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,NaN
453698,FERG,ART,2020-06-30,2021-02-12,2020-07-31,2021-03-09,0.0,1.345600e+04,NaN,8.057000e+03,...,USD,United Kingdom,2021-03-09,2021-03-09,2021-03-08,2021-03-09,2019-06-30,2020-06-30,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.fergusonplc.com
453709,ACQRU,ART,2020-12-31,2021-03-05,2020-12-31,2021-03-09,0.0,1.244970e+05,NaN,1.316200e+04,...,USD,New York; U.S.A,2021-03-09,2021-03-09,2021-03-09,2021-03-09,2020-12-31,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,NaN

In [15]:
#filter for financials in USD currency
fundamentals = fundamentals[fundamentals.currency=="USD"]
fundamentals

,ticker,dimension,calendardate,datekey,reportperiod,lastupdated_x,accoci,assets,assetsavg,assetsc,...,currency,location,lastupdated_y,firstadded,firstpricedate,lastpricedate,firstquarter,lastquarter,secfilings,companysite
14,A,ART,2016-03-31,2016-06-07,2016-04-30,2021-03-02,-299000000.0,7.640000e+09,7.418000e+09,3.488000e+09,...,USD,California; U.S.A,2021-03-02,2014-09-26,1999-11-18,2021-03-09,1997-06-30,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.agilent.com
15,A,ART,2016-06-30,2016-09-07,2016-07-31,2021-03-02,-345000000.0,7.734000e+09,7.538750e+09,3.530000e+09,...,USD,California; U.S.A,2021-03-02,2014-09-26,1999-11-18,2021-03-09,1997-06-30,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.agilent.com
16,A,ART,2016-09-30,2016-12-20,2016-10-31,2021-03-02,-503000000.0,7.802000e+09,7.619500e+09,3.635000e+09,...,USD,California; U.S.A,2021-03-02,2014-09-26,1999-11-18,2021-03-09,1997-06-30,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.agilent.com
17,A,ART,2016-12-31,2017-03-08,2017-01-31,2021-03-02,-489000000.0,7.872000e+09,7.762000e+09,3.635000e+09,...,USD,California; U.S.A,2021-03-02,2014-09-26,1999-11-18,2021-03-09,1997-06-30,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.agilent.com
18,A,ART,2017-03-31,2017-06-06,2017-04-30,2021-03-02,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,...,USD,California; U.S.A,2021-03-02,2014-09-26,1999-11-18,2021-03-09,1997-06-30,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.agilent.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453686,PDOT.U,ART,2020-12-31,2021-03-01,2021-01-14,2021-03-09,0.0,5.361000e+04,NaN,NaN,...,USD,Texas; U.S.A,2021-03-09,2021-03-09,2021-03-09,2021-03-09,2020-12-31,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,NaN
453690,SVFB,ART,2020-12-31,2021-03-04,2020-12-31,2021-03-09,0.0,1.341800e+05,NaN,7.430000e+03,...,USD,California; U.S.A,2021-03-09,2021-03-09,2021-03-09,2021-03-09,2020-12-31,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,NaN
453694,SVFC,ART,2020-12-31,2021-03-04,2020-12-31,2021-03-09,0.0,1.329040e+05,NaN,6.154000e+03,...,USD,California; U.S.A,2021-03-09,2021-03-09,2021-03-09,2021-03-09,2020-12-31,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,NaN
453698,FERG,ART,2020-06-30,2021-02-12,2020-07-31,2021-03-09,0.0,1.345600e+04,NaN,8.057000e+03,...,USD,United Kingdom,2021-03-09,2021-03-09,2021-03-08,2021-03-09,2019-06-30,2020-06-30,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.fergusonplc.com
453709,ACQRU,ART,2020-12-31,2021-03-05,2020-12-31,2021-03-09,0.0,1.244970e+05,NaN,1.316200e+04,...,USD,New York; U.S.A,2021-03-09,2021-03-09,2021-03-09,2021-03-09,2020-12-31,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,NaN

In [16]:
#group by ticker, sort by calendardate
fundamentals = fundamentals.sort_values(['calendardate'], ascending=True) \
        .groupby(['ticker'], sort=False) \
        .apply(lambda x: x.sort_values(['calendardate'], ascending=True)) \
        .reset_index(drop=True)

In [17]:
fundamentals

,ticker,dimension,calendardate,datekey,reportperiod,lastupdated_x,accoci,assets,assetsavg,assetsc,...,currency,location,lastupdated_y,firstadded,firstpricedate,lastpricedate,firstquarter,lastquarter,secfilings,companysite
0,A,ART,2016-03-31,2016-06-07,2016-04-30,2021-03-02,-299000000.0,7.640000e+09,7.418000e+09,3.488000e+09,...,USD,California; U.S.A,2021-03-02,2014-09-26,1999-11-18,2021-03-09,1997-06-30,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.agilent.com
1,A,ART,2016-06-30,2016-09-07,2016-07-31,2021-03-02,-345000000.0,7.734000e+09,7.538750e+09,3.530000e+09,...,USD,California; U.S.A,2021-03-02,2014-09-26,1999-11-18,2021-03-09,1997-06-30,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.agilent.com
2,A,ART,2016-09-30,2016-12-20,2016-10-31,2021-03-02,-503000000.0,7.802000e+09,7.619500e+09,3.635000e+09,...,USD,California; U.S.A,2021-03-02,2014-09-26,1999-11-18,2021-03-09,1997-06-30,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.agilent.com
3,A,ART,2016-12-31,2017-03-08,2017-01-31,2021-03-02,-489000000.0,7.872000e+09,7.762000e+09,3.635000e+09,...,USD,California; U.S.A,2021-03-02,2014-09-26,1999-11-18,2021-03-09,1997-06-30,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.agilent.com
4,A,ART,2017-03-31,2017-06-06,2017-04-30,2021-03-02,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,...,USD,California; U.S.A,2021-03-02,2014-09-26,1999-11-18,2021-03-09,1997-06-30,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.agilent.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97242,FACA.U,ART,2020-12-31,2021-02-11,2020-12-31,2021-02-19,0.0,7.436600e+04,NaN,NaN,...,USD,California; U.S.A,2021-02-19,2021-02-19,2021-02-19,2021-03-09,2020-12-31,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,NaN
97243,CFVIU,ART,2020-12-31,2021-02-12,2020-12-31,2021-02-19,0.0,2.058050e+05,NaN,2.500000e+04,...,USD,New York; U.S.A,2021-02-19,2021-02-19,2021-02-19,2021-03-09,2020-12-31,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,NaN
97244,IBER.U,ART,2020-12-31,2021-02-22,2020-12-31,2021-02-28,0.0,6.763660e+05,NaN,NaN,...,USD,Pennsylvania; U.S.A,2021-02-28,2021-02-28,2021-02-26,2021-03-09,2020-12-31,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,NaN
97245,GSQD.U,ART,2020-12-31,2021-01-28,2020-12-31,2021-02-07,0.0,2.281800e+05,NaN,NaN,...,USD,Illinois; U.S.A,2021-02-07,2021-02-06,2021-02-05,2021-03-09,2020-12-31,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,NaN
97246,ACQRU,ART,2020-12-31,2021-03-05,2020-12-31,2021-03-09,0.0,1.244970e+05,NaN,1.316200e+04,...,USD,New York; U.S.A,2021-03-09,2021-03-09,2021-03-09,2021-03-09,2020-12-31,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,NaN

In [18]:
#filter fundamentals data for only those tickers w/ analyst rating history (ticks)
fundamentals = pd.merge(fundamentals, ticks, how="inner", on="ticker")

In [19]:
fundamentals

,ticker,dimension,calendardate,datekey,reportperiod,lastupdated_x,accoci,assets,assetsavg,assetsc,...,currency,location,lastupdated_y,firstadded,firstpricedate,lastpricedate,firstquarter,lastquarter,secfilings,companysite
0,A,ART,2016-03-31,2016-06-07,2016-04-30,2021-03-02,-299000000.0,7.640000e+09,7.418000e+09,3.488000e+09,...,USD,California; U.S.A,2021-03-02,2014-09-26,1999-11-18,2021-03-09,1997-06-30,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.agilent.com
1,A,ART,2016-06-30,2016-09-07,2016-07-31,2021-03-02,-345000000.0,7.734000e+09,7.538750e+09,3.530000e+09,...,USD,California; U.S.A,2021-03-02,2014-09-26,1999-11-18,2021-03-09,1997-06-30,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.agilent.com
2,A,ART,2016-09-30,2016-12-20,2016-10-31,2021-03-02,-503000000.0,7.802000e+09,7.619500e+09,3.635000e+09,...,USD,California; U.S.A,2021-03-02,2014-09-26,1999-11-18,2021-03-09,1997-06-30,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.agilent.com
3,A,ART,2016-12-31,2017-03-08,2017-01-31,2021-03-02,-489000000.0,7.872000e+09,7.762000e+09,3.635000e+09,...,USD,California; U.S.A,2021-03-02,2014-09-26,1999-11-18,2021-03-09,1997-06-30,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.agilent.com
4,A,ART,2017-03-31,2017-06-06,2017-04-30,2021-03-02,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,...,USD,California; U.S.A,2021-03-02,2014-09-26,1999-11-18,2021-03-09,1997-06-30,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.agilent.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74045,DASH,ART,2020-09-30,2020-12-07,2020-09-30,2021-03-06,1000000.0,2.874000e+09,NaN,1.990000e+09,...,USD,California; U.S.A,2021-03-06,2020-12-09,2020-12-09,2021-03-09,2018-12-31,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.doordash.com
74046,DASH,ART,2020-12-31,2021-03-05,2020-12-31,2021-03-06,0.0,6.353000e+09,NaN,5.517000e+09,...,USD,California; U.S.A,2021-03-06,2020-12-09,2020-12-09,2021-03-09,2018-12-31,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.doordash.com
74047,CHK,ART,2020-12-31,2021-03-01,2020-12-31,2021-03-01,45000000.0,6.584000e+09,NaN,1.108000e+09,...,USD,Oklahoma; U.S.A,2021-03-01,2021-03-01,2021-02-10,2021-03-09,2019-12-31,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,NaN
74048,OAS,ART,2020-12-31,2021-03-08,2020-12-31,2021-03-08,0.0,2.159037e+09,NaN,2.716170e+08,...,USD,Texas; U.S.A,2021-03-08,2021-03-08,2020-11-20,2021-03-09,2020-12-31,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.oasispetroleum.com
74049,WFG,ART,2020-12-31,2021-02-12,2020-12-31,2021-02-12,105000000.0,5.320000e+09,NaN,1.701000e+09,...,USD,British Columbia; Canada,2021-02-12,2021-02-01,2021-02-01,2021-03-09,2019-12-31,2020-12-31,https://www.sec.gov/cgi-bin/browse-edgar?actio...,http://www.westfraser.com

In [20]:
#drop columns in fundamentals df that will not be used in further preprocessing steps/modeling
fundamentals.drop([
 'dimension',
 'datekey',
 'reportperiod',
 'lastupdated_x',
 'table',
 'permaticker',
 'isdelisted',
 'category',
 'cusips',
 'siccode',
 'sicsector',
 'sicindustry',
 'famasector',
 'famaindustry',
 'relatedtickers',
 'location',
 'lastupdated_y',
 'firstadded',
 'firstpricedate',
 'lastpricedate',
 'firstquarter',
 'lastquarter',
 'secfilings',
 'companysite',
 'currency',
 'cashnequsd',
 'debtusd',
 'ebitusd',
 'ebitdausd',
 'epsusd',
 'equityusd',
 'netinccmnusd',
 'revenueusd',
 'fxusd',
 'scalemarketcap',
 'scalerevenue',
 'price',
 'divyield',
 'ev',
 'evebit',
 'evebitda',
 'marketcap',
 'pb',
 'pe',
 'pe1'
 ], axis=1, inplace=True)
fundamentals

,ticker,calendardate,accoci,assets,assetsavg,assetsc,assetsnc,assetturnover,bvps,capex,...,tangibles,taxassets,taxexp,taxliabilities,tbvps,workingcapital,name,exchange,sector,industry
0,A,2016-03-31,-299000000.0,7.640000e+09,7.418000e+09,3.488000e+09,4.152000e+09,0.552,12.767,-108000000.0,...,4.594000e+09,0.0,68000000.0,0.0,14.092,2.355000e+09,Agilent Technologies Inc,NYSE,Healthcare,Diagnostics & Research
1,A,2016-06-30,-345000000.0,7.734000e+09,7.538750e+09,3.530000e+09,4.204000e+09,0.547,13.363,-113000000.0,...,4.767000e+09,0.0,55000000.0,0.0,14.668,2.379000e+09,Agilent Technologies Inc,NYSE,Healthcare,Diagnostics & Research
2,A,2016-09-30,-503000000.0,7.802000e+09,7.619500e+09,3.635000e+09,4.167000e+09,0.551,13.015,-139000000.0,...,4.877000e+09,0.0,82000000.0,0.0,14.960,2.690000e+09,Agilent Technologies Inc,NYSE,Healthcare,Diagnostics & Research
3,A,2016-12-31,-489000000.0,7.872000e+09,7.762000e+09,3.635000e+09,4.237000e+09,0.546,13.345,-133000000.0,...,4.898000e+09,0.0,86000000.0,0.0,15.211,2.546000e+09,Agilent Technologies Inc,NYSE,Healthcare,Diagnostics & Research
4,A,2017-03-31,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,4.216000e+09,0.550,13.620,-151000000.0,...,5.075000e+09,0.0,87000000.0,0.0,15.810,2.613000e+09,Agilent Technologies Inc,NYSE,Healthcare,Diagnostics & Research
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74045,DASH,2020-09-30,1000000.0,2.874000e+09,NaN,1.990000e+09,8.840000e+08,NaN,NaN,NaN,...,2.509000e+09,0.0,NaN,0.0,NaN,1.156000e+09,DoorDash Inc,NYSE,Technology,Internet Content & Information
74046,DASH,2020-12-31,0.0,6.353000e+09,NaN,5.517000e+09,8.360000e+08,NaN,75.333,-159000000.0,...,5.963000e+09,0.0,3000000.0,0.0,95.576,4.115000e+09,DoorDash Inc,NYSE,Technology,Internet Content & Information
74047,CHK,2020-12-31,45000000.0,6.584000e+09,NaN,1.108000e+09,5.476000e+09,NaN,-546.506,-992000000.0,...,6.584000e+09,0.0,-19000000.0,0.0,673.693,-1.986000e+09,Chesapeake Energy Corp,NASDAQ,Energy,Oil & Gas E&P
74048,OAS,2020-12-31,0.0,2.159037e+09,NaN,2.716170e+08,1.887420e+09,NaN,NaN,NaN,...,2.044836e+09,0.0,NaN,147481000.0,NaN,-6.961400e+07,Oasis Petroleum Inc,NASDAQ,Energy,Oil & Gas E&P
74049,WFG,2020-12-31,105000000.0,5.320000e+09,NaN,1.701000e+09,3.619000e+09,NaN,25.616,-227000000.0,...,4.094000e+09,22000000.0,266000000.0,460000000.0,33.241,1.028000e+09,West Fraser Timber Co Ltd,NYSE,Basic Materials,Lumber & Wood Production

In [21]:
#create new field that identifies quarter - used later autoregressive timeseries feature engineering
fundamentals["quarter"] = pd.PeriodIndex(pd.to_datetime(fundamentals.calendardate), freq='Q')
fundamentals["quarter"] = fundamentals["quarter"].astype(str)
fundamentals["quart"] = fundamentals.quarter.str[4:]
fundamentals["year"] = fundamentals.quarter.str[0:4]
del fundamentals["quarter"]
fundamentals

,ticker,calendardate,accoci,assets,assetsavg,assetsc,assetsnc,assetturnover,bvps,capex,...,taxexp,taxliabilities,tbvps,workingcapital,name,exchange,sector,industry,quart,year
0,A,2016-03-31,-299000000.0,7.640000e+09,7.418000e+09,3.488000e+09,4.152000e+09,0.552,12.767,-108000000.0,...,68000000.0,0.0,14.092,2.355000e+09,Agilent Technologies Inc,NYSE,Healthcare,Diagnostics & Research,Q1,2016
1,A,2016-06-30,-345000000.0,7.734000e+09,7.538750e+09,3.530000e+09,4.204000e+09,0.547,13.363,-113000000.0,...,55000000.0,0.0,14.668,2.379000e+09,Agilent Technologies Inc,NYSE,Healthcare,Diagnostics & Research,Q2,2016
2,A,2016-09-30,-503000000.0,7.802000e+09,7.619500e+09,3.635000e+09,4.167000e+09,0.551,13.015,-139000000.0,...,82000000.0,0.0,14.960,2.690000e+09,Agilent Technologies Inc,NYSE,Healthcare,Diagnostics & Research,Q3,2016
3,A,2016-12-31,-489000000.0,7.872000e+09,7.762000e+09,3.635000e+09,4.237000e+09,0.546,13.345,-133000000.0,...,86000000.0,0.0,15.211,2.546000e+09,Agilent Technologies Inc,NYSE,Healthcare,Diagnostics & Research,Q4,2016
4,A,2017-03-31,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,4.216000e+09,0.550,13.620,-151000000.0,...,87000000.0,0.0,15.810,2.613000e+09,Agilent Technologies Inc,NYSE,Healthcare,Diagnostics & Research,Q1,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74045,DASH,2020-09-30,1000000.0,2.874000e+09,NaN,1.990000e+09,8.840000e+08,NaN,NaN,NaN,...,NaN,0.0,NaN,1.156000e+09,DoorDash Inc,NYSE,Technology,Internet Content & Information,Q3,2020
74046,DASH,2020-12-31,0.0,6.353000e+09,NaN,5.517000e+09,8.360000e+08,NaN,75.333,-159000000.0,...,3000000.0,0.0,95.576,4.115000e+09,DoorDash Inc,NYSE,Technology,Internet Content & Information,Q4,2020
74047,CHK,2020-12-31,45000000.0,6.584000e+09,NaN,1.108000e+09,5.476000e+09,NaN,-546.506,-992000000.0,...,-19000000.0,0.0,673.693,-1.986000e+09,Chesapeake Energy Corp,NASDAQ,Energy,Oil & Gas E&P,Q4,2020
74048,OAS,2020-12-31,0.0,2.159037e+09,NaN,2.716170e+08,1.887420e+09,NaN,NaN,NaN,...,NaN,147481000.0,NaN,-6.961400e+07,Oasis Petroleum Inc,NASDAQ,Energy,Oil & Gas E&P,Q4,2020
74049,WFG,2020-12-31,105000000.0,5.320000e+09,NaN,1.701000e+09,3.619000e+09,NaN,25.616,-227000000.0,...,266000000.0,460000000.0,33.241,1.028000e+09,West Fraser Timber Co Ltd,NYSE,Basic Materials,Lumber & Wood Production,Q4,2020

In [22]:
#calculate multi-period (n) percent change of specified features
for n in [1,2,3]:
    fundamentals = fundamentals.join(fundamentals.groupby(['ticker','quart'])[
            [
                'revenue',
                'gp',
                'ebitda',
                'opinc',
                'netinc',
                'eps',
                'assets',
                'ncfo',
                'ncf',
                'equity'
            ]
        ].apply(lambda x : x.pct_change(n)).add_suffix(f"_{n}y_pct")).replace([np.inf, -np.inf], np.nan)

In [23]:
fundamentals

,ticker,calendardate,accoci,assets,assetsavg,assetsc,assetsnc,assetturnover,bvps,capex,...,revenue_3y_pct,gp_3y_pct,ebitda_3y_pct,opinc_3y_pct,netinc_3y_pct,eps_3y_pct,assets_3y_pct,ncfo_3y_pct,ncf_3y_pct,equity_3y_pct
0,A,2016-03-31,-299000000.0,7.640000e+09,7.418000e+09,3.488000e+09,4.152000e+09,0.552,12.767,-108000000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A,2016-06-30,-345000000.0,7.734000e+09,7.538750e+09,3.530000e+09,4.204000e+09,0.547,13.363,-113000000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A,2016-09-30,-503000000.0,7.802000e+09,7.619500e+09,3.635000e+09,4.167000e+09,0.551,13.015,-139000000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A,2016-12-31,-489000000.0,7.872000e+09,7.762000e+09,3.635000e+09,4.237000e+09,0.546,13.345,-133000000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A,2017-03-31,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,4.216000e+09,0.550,13.620,-151000000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74045,DASH,2020-09-30,1000000.0,2.874000e+09,NaN,1.990000e+09,8.840000e+08,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74046,DASH,2020-12-31,0.0,6.353000e+09,NaN,5.517000e+09,8.360000e+08,NaN,75.333,-159000000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74047,CHK,2020-12-31,45000000.0,6.584000e+09,NaN,1.108000e+09,5.476000e+09,NaN,-546.506,-992000000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74048,OAS,2020-12-31,0.0,2.159037e+09,NaN,2.716170e+08,1.887420e+09,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74049,WFG,2020-12-31,105000000.0,5.320000e+09,NaN,1.701000e+09,3.619000e+09,NaN,25.616,-227000000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Null Values

In [24]:
#investigate null values
fundamentals.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 74050 entries, 0 to 74049
Data columns (total 125 columns):
 #    Column          Non-Null Count  Dtype
---   ------          --------------  -----
 0    ticker          74050 non-null  object
 1    calendardate    74050 non-null  object
 2    accoci          74048 non-null  float64
 3    assets          74048 non-null  float64
 4    assetsavg       70736 non-null  float64
 5    assetsc         58794 non-null  float64
 6    assetsnc        58794 non-null  float64
 7    assetturnover   70107 non-null  float64
 8    bvps            73800 non-null  float64
 9    capex           70644 non-null  float64
 10   cashneq         74048 non-null  float64
 11   cor             71146 non-null  float64
 12   consolinc       71143 non-null  float64
 13   currentratio    58707 non-null  float64
 14   de              74042 non-null  float64
 15   debt            74048 non-null  float64
 16   debtc           58802 non-null  float64
 17   debtnc          58798 non-null  float64
 18   deferredrev     74048 non-null  float64
 19   depamor         70645 non-null  float64
 20   deposits        74048 non-null  float64
 21   dps             73805 non-null  float64
 22   ebit            71143 non-null  float64
 23   ebitda          70630 non-null  float64
 24   ebitdamargin    66656 non-null  float64
 25   ebt             71143 non-null  float64
 26   eps             70657 non-null  float64
 27   epsdil          70476 non-null  float64
 28   equity          74048 non-null  float64
 29   equityavg       70736 non-null  float64
 30   fcf             70636 non-null  float64
 31   fcfps           70633 non-null  float64
 32   gp              71146 non-null  float64
 33   grossmargin     67080 non-null  float64
 34   intangibles     74048 non-null  float64
 35   intexp          71146 non-null  float64
 36   invcap          74048 non-null  float64
 37   invcapavg       70736 non-null  float64
 38   inventory       74048 non-null  float64
 39   investments     74048 non-null  float64
 40   investmentsc    58794 non-null  float64
 41   investmentsnc   58794 non-null  float64
 42   liabilities     74048 non-null  float64
 43   liabilitiesc    58794 non-null  float64
 44   liabilitiesnc   58794 non-null  float64
 45   ncf             70643 non-null  float64
 46   ncfbus          70644 non-null  float64
 47   ncfcommon       70643 non-null  float64
 48   ncfdebt         70643 non-null  float64
 49   ncfdiv          70643 non-null  float64
 50   ncff            70643 non-null  float64
 51   ncfi            70644 non-null  float64
 52   ncfinv          70644 non-null  float64
 53   ncfo            70637 non-null  float64
 54   ncfx            70577 non-null  float64
 55   netinc          71143 non-null  float64
 56   netinccmn       71143 non-null  float64
 57   netincdis       71143 non-null  float64
 58   netincnci       71143 non-null  float64
 59   netmargin       67077 non-null  float64
 60   opex            71146 non-null  float64
 61   opinc           71146 non-null  float64
 62   payables        74048 non-null  float64
 63   payoutratio     70388 non-null  float64
 64   ppnenet         74048 non-null  float64
 65   prefdivis       71143 non-null  float64
 66   ps              66102 non-null  float64
 67   ps1             66102 non-null  float64
 68   receivables     74048 non-null  float64
 69   retearn         71333 non-null  float64
 70   revenue         71146 non-null  float64
 71   rnd             71145 non-null  float64
 72   roa             70106 non-null  float64
 73   roe             70106 non-null  float64
 74   roic            70105 non-null  float64
 75   ros             67077 non-null  float64
 76   sbcomp          70637 non-null  float64
 77   sgna            71146 non-null  float64
 78   sharefactor     74050 non-null  float64
 79   sharesbas       74044 non-null  float64
 80   shareswa        73802 non-null  float64
 81   shareswadil     57335 non-null  float64
 82   sps             71143 non-null  float64
 83   tangibles       74048 non-null  float64
 84   taxassets       74048 non-null  float64
 85   taxexp          71145 non-null  float64
 86   taxliabilities  74048 non-null  float64
 87   tbvps           73800 non-null  float64
 88   workingcapital  58712 non-null  float64
 89   name            74050 non-null  object
 90   exchange        74050 non-null  object
 91   sector          74021 non-null  object
 92   industry        74021 non-null  object
 93   quart           74050 non-null  object
 94   year            74050 non-null  object
 95   revenue_1y_pct  52117 non-null  float64
 96   gp_1y_pct       52122 non-null  float64
 97   ebitda_1y_pct   54783 non-null  float64
 98   opinc_1y_pct    55138 non-null  float64
 99   netinc_1y_pct   55128 non-null  float64
 100  eps_1y_pct      54518 non-null  float64
 101  assets_1y_pct   57323 non-null  float64
 102  ncfo_1y_pct     54775 non-null  float64
 103  ncf_1y_pct      54639 non-null  float64
 104  equity_1y_pct   57324 non-null  float64
 105  revenue_2y_pct  37698 non-null  float64
 106  gp_2y_pct       37698 non-null  float64
 107  ebitda_2y_pct   39498 non-null  float64
 108  opinc_2y_pct    39747 non-null  float64
 109  netinc_2y_pct   39737 non-null  float64
 110  eps_2y_pct      39248 non-null  float64
 111  assets_2y_pct   41377 non-null  float64
 112  ncfo_2y_pct     39492 non-null  float64
 113  ncf_2y_pct      39397 non-null  float64
 114  equity_2y_pct   41379 non-null  float64
 115  revenue_3y_pct  24054 non-null  float64
 116  gp_3y_pct       24054 non-null  float64
 117  ebitda_3y_pct   25143 non-null  float64
 118  opinc_3y_pct    25305 non-null  float64
 119  netinc_3y_pct   25296 non-null  float64
 120  eps_3y_pct      24941 non-null  float64
 121  assets_3y_pct   26279 non-null  float64
 122  ncfo_3y_pct     25140 non-null  float64
 123  ncf_3y_pct      25079 non-null  float64
 124  equity_3y_pct   26281 non-null  float64
dtypes: float64(117), object(8)
memory usage: 73.2+ MB

<ipython-input-24-4d9dd3b67a66>:2: FutureWarning: null_counts is deprecated. Use show_counts instead
  fundamentals.info(verbose=True, null_counts=True)

In [25]:
#delete values w/out sector/industry information
fundamentals = fundamentals[fundamentals['sector'].notna()]
fundamentals = fundamentals[fundamentals['industry'].notna()]

In [26]:
#investigate null values
fundamentals.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 74021 entries, 0 to 74049
Data columns (total 125 columns):
 #    Column          Non-Null Count  Dtype
---   ------          --------------  -----
 0    ticker          74021 non-null  object
 1    calendardate    74021 non-null  object
 2    accoci          74019 non-null  float64
 3    assets          74019 non-null  float64
 4    assetsavg       70710 non-null  float64
 5    assetsc         58787 non-null  float64
 6    assetsnc        58787 non-null  float64
 7    assetturnover   70081 non-null  float64
 8    bvps            73771 non-null  float64
 9    capex           70618 non-null  float64
 10   cashneq         74019 non-null  float64
 11   cor             71120 non-null  float64
 12   consolinc       71117 non-null  float64
 13   currentratio    58700 non-null  float64
 14   de              74013 non-null  float64
 15   debt            74019 non-null  float64
 16   debtc           58793 non-null  float64
 17   debtnc          58789 non-null  float64
 18   deferredrev     74019 non-null  float64
 19   depamor         70619 non-null  float64
 20   deposits        74019 non-null  float64
 21   dps             73776 non-null  float64
 22   ebit            71117 non-null  float64
 23   ebitda          70604 non-null  float64
 24   ebitdamargin    66632 non-null  float64
 25   ebt             71117 non-null  float64
 26   eps             70631 non-null  float64
 27   epsdil          70450 non-null  float64
 28   equity          74019 non-null  float64
 29   equityavg       70710 non-null  float64
 30   fcf             70610 non-null  float64
 31   fcfps           70607 non-null  float64
 32   gp              71120 non-null  float64
 33   grossmargin     67056 non-null  float64
 34   intangibles     74019 non-null  float64
 35   intexp          71120 non-null  float64
 36   invcap          74019 non-null  float64
 37   invcapavg       70710 non-null  float64
 38   inventory       74019 non-null  float64
 39   investments     74019 non-null  float64
 40   investmentsc    58787 non-null  float64
 41   investmentsnc   58787 non-null  float64
 42   liabilities     74019 non-null  float64
 43   liabilitiesc    58785 non-null  float64
 44   liabilitiesnc   58785 non-null  float64
 45   ncf             70617 non-null  float64
 46   ncfbus          70618 non-null  float64
 47   ncfcommon       70617 non-null  float64
 48   ncfdebt         70617 non-null  float64
 49   ncfdiv          70617 non-null  float64
 50   ncff            70617 non-null  float64
 51   ncfi            70618 non-null  float64
 52   ncfinv          70618 non-null  float64
 53   ncfo            70611 non-null  float64
 54   ncfx            70551 non-null  float64
 55   netinc          71117 non-null  float64
 56   netinccmn       71117 non-null  float64
 57   netincdis       71117 non-null  float64
 58   netincnci       71117 non-null  float64
 59   netmargin       67053 non-null  float64
 60   opex            71120 non-null  float64
 61   opinc           71120 non-null  float64
 62   payables        74019 non-null  float64
 63   payoutratio     70362 non-null  float64
 64   ppnenet         74019 non-null  float64
 65   prefdivis       71117 non-null  float64
 66   ps              66095 non-null  float64
 67   ps1             66095 non-null  float64
 68   receivables     74019 non-null  float64
 69   retearn         71304 non-null  float64
 70   revenue         71120 non-null  float64
 71   rnd             71119 non-null  float64
 72   roa             70080 non-null  float64
 73   roe             70080 non-null  float64
 74   roic            70079 non-null  float64
 75   ros             67053 non-null  float64
 76   sbcomp          70611 non-null  float64
 77   sgna            71120 non-null  float64
 78   sharefactor     74021 non-null  float64
 79   sharesbas       74015 non-null  float64
 80   shareswa        73773 non-null  float64
 81   shareswadil     57309 non-null  float64
 82   sps             71117 non-null  float64
 83   tangibles       74019 non-null  float64
 84   taxassets       74019 non-null  float64
 85   taxexp          71119 non-null  float64
 86   taxliabilities  74019 non-null  float64
 87   tbvps           73771 non-null  float64
 88   workingcapital  58705 non-null  float64
 89   name            74021 non-null  object
 90   exchange        74021 non-null  object
 91   sector          74021 non-null  object
 92   industry        74021 non-null  object
 93   quart           74021 non-null  object
 94   year            74021 non-null  object
 95   revenue_1y_pct  52101 non-null  float64
 96   gp_1y_pct       52106 non-null  float64
 97   ebitda_1y_pct   54765 non-null  float64
 98   opinc_1y_pct    55120 non-null  float64
 99   netinc_1y_pct   55110 non-null  float64
 100  eps_1y_pct      54500 non-null  float64
 101  assets_1y_pct   57302 non-null  float64
 102  ncfo_1y_pct     54757 non-null  float64
 103  ncf_1y_pct      54621 non-null  float64
 104  equity_1y_pct   57303 non-null  float64
 105  revenue_2y_pct  37686 non-null  float64
 106  gp_2y_pct       37686 non-null  float64
 107  ebitda_2y_pct   39486 non-null  float64
 108  opinc_2y_pct    39735 non-null  float64
 109  netinc_2y_pct   39725 non-null  float64
 110  eps_2y_pct      39236 non-null  float64
 111  assets_2y_pct   41364 non-null  float64
 112  ncfo_2y_pct     39480 non-null  float64
 113  ncf_2y_pct      39385 non-null  float64
 114  equity_2y_pct   41366 non-null  float64
 115  revenue_3y_pct  24046 non-null  float64
 116  gp_3y_pct       24046 non-null  float64
 117  ebitda_3y_pct   25135 non-null  float64
 118  opinc_3y_pct    25297 non-null  float64
 119  netinc_3y_pct   25288 non-null  float64
 120  eps_3y_pct      24933 non-null  float64
 121  assets_3y_pct   26271 non-null  float64
 122  ncfo_3y_pct     25132 non-null  float64
 123  ncf_3y_pct      25071 non-null  float64
 124  equity_3y_pct   26273 non-null  float64
dtypes: float64(117), object(8)
memory usage: 71.2+ MB

<ipython-input-26-4d9dd3b67a66>:2: FutureWarning: null_counts is deprecated. Use show_counts instead
  fundamentals.info(verbose=True, null_counts=True)

In [27]:
#delete values w/out core financial statement metrics
fundamentals = fundamentals[fundamentals['assets'].notna()]
fundamentals = fundamentals[fundamentals['gp'].notna()]
fundamentals = fundamentals[fundamentals['ebitda'].notna()]
fundamentals = fundamentals[fundamentals['opinc'].notna()]
fundamentals = fundamentals[fundamentals['netinc'].notna()]
fundamentals = fundamentals[fundamentals['eps'].notna()]
fundamentals = fundamentals[fundamentals['ncfo'].notna()]
fundamentals = fundamentals[fundamentals['ncf'].notna()]
fundamentals = fundamentals[fundamentals['equity'].notna()]

In [28]:
#investigate null values
fundamentals.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 70135 entries, 0 to 74049
Data columns (total 125 columns):
 #    Column          Non-Null Count  Dtype
---   ------          --------------  -----
 0    ticker          70135 non-null  object
 1    calendardate    70135 non-null  object
 2    accoci          70135 non-null  float64
 3    assets          70135 non-null  float64
 4    assetsavg       69297 non-null  float64
 5    assetsc         55448 non-null  float64
 6    assetsnc        55448 non-null  float64
 7    assetturnover   69297 non-null  float64
 8    bvps            70135 non-null  float64
 9    capex           70134 non-null  float64
 10   cashneq         70135 non-null  float64
 11   cor             70135 non-null  float64
 12   consolinc       70135 non-null  float64
 13   currentratio    55379 non-null  float64
 14   de              70134 non-null  float64
 15   debt            70135 non-null  float64
 16   debtc           55397 non-null  float64
 17   debtnc          55395 non-null  float64
 18   deferredrev     70135 non-null  float64
 19   depamor         70135 non-null  float64
 20   deposits        70135 non-null  float64
 21   dps             70135 non-null  float64
 22   ebit            70135 non-null  float64
 23   ebitda          70135 non-null  float64
 24   ebitdamargin    66174 non-null  float64
 25   ebt             70135 non-null  float64
 26   eps             70135 non-null  float64
 27   epsdil          69960 non-null  float64
 28   equity          70135 non-null  float64
 29   equityavg       69297 non-null  float64
 30   fcf             70134 non-null  float64
 31   fcfps           70134 non-null  float64
 32   gp              70135 non-null  float64
 33   grossmargin     66174 non-null  float64
 34   intangibles     70135 non-null  float64
 35   intexp          70135 non-null  float64
 36   invcap          70135 non-null  float64
 37   invcapavg       69297 non-null  float64
 38   inventory       70135 non-null  float64
 39   investments     70135 non-null  float64
 40   investmentsc    55448 non-null  float64
 41   investmentsnc   55448 non-null  float64
 42   liabilities     70135 non-null  float64
 43   liabilitiesc    55391 non-null  float64
 44   liabilitiesnc   55391 non-null  float64
 45   ncf             70135 non-null  float64
 46   ncfbus          70134 non-null  float64
 47   ncfcommon       70135 non-null  float64
 48   ncfdebt         70135 non-null  float64
 49   ncfdiv          70135 non-null  float64
 50   ncff            70135 non-null  float64
 51   ncfi            70134 non-null  float64
 52   ncfinv          70134 non-null  float64
 53   ncfo            70135 non-null  float64
 54   ncfx            70070 non-null  float64
 55   netinc          70135 non-null  float64
 56   netinccmn       70135 non-null  float64
 57   netincdis       70135 non-null  float64
 58   netincnci       70135 non-null  float64
 59   netmargin       66174 non-null  float64
 60   opex            70135 non-null  float64
 61   opinc           70135 non-null  float64
 62   payables        70135 non-null  float64
 63   payoutratio     69875 non-null  float64
 64   ppnenet         70135 non-null  float64
 65   prefdivis       70135 non-null  float64
 66   ps              65496 non-null  float64
 67   ps1             65496 non-null  float64
 68   receivables     70135 non-null  float64
 69   retearn         67846 non-null  float64
 70   revenue         70135 non-null  float64
 71   rnd             70135 non-null  float64
 72   roa             69297 non-null  float64
 73   roe             69297 non-null  float64
 74   roic            69296 non-null  float64
 75   ros             66174 non-null  float64
 76   sbcomp          70135 non-null  float64
 77   sgna            70135 non-null  float64
 78   sharefactor     70135 non-null  float64
 79   sharesbas       70134 non-null  float64
 80   shareswa        70135 non-null  float64
 81   shareswadil     56894 non-null  float64
 82   sps             70135 non-null  float64
 83   tangibles       70135 non-null  float64
 84   taxassets       70135 non-null  float64
 85   taxexp          70135 non-null  float64
 86   taxliabilities  70135 non-null  float64
 87   tbvps           70135 non-null  float64
 88   workingcapital  55381 non-null  float64
 89   name            70135 non-null  object
 90   exchange        70135 non-null  object
 91   sector          70135 non-null  object
 92   industry        70135 non-null  object
 93   quart           70135 non-null  object
 94   year            70135 non-null  object
 95   revenue_1y_pct  51583 non-null  float64
 96   gp_1y_pct       51585 non-null  float64
 97   ebitda_1y_pct   54311 non-null  float64
 98   opinc_1y_pct    54546 non-null  float64
 99   netinc_1y_pct   54544 non-null  float64
 100  eps_1y_pct      54137 non-null  float64
 101  assets_1y_pct   56433 non-null  float64
 102  ncfo_1y_pct     54303 non-null  float64
 103  ncf_1y_pct      54170 non-null  float64
 104  equity_1y_pct   56434 non-null  float64
 105  revenue_2y_pct  37346 non-null  float64
 106  gp_2y_pct       37345 non-null  float64
 107  ebitda_2y_pct   39201 non-null  float64
 108  opinc_2y_pct    39374 non-null  float64
 109  netinc_2y_pct   39370 non-null  float64
 110  eps_2y_pct      38995 non-null  float64
 111  assets_2y_pct   40930 non-null  float64
 112  ncfo_2y_pct     39196 non-null  float64
 113  ncf_2y_pct      39101 non-null  float64
 114  equity_2y_pct   40931 non-null  float64
 115  revenue_3y_pct  23828 non-null  float64
 116  gp_3y_pct       23828 non-null  float64
 117  ebitda_3y_pct   24957 non-null  float64
 118  opinc_3y_pct    25071 non-null  float64
 119  netinc_3y_pct   25067 non-null  float64
 120  eps_3y_pct      24775 non-null  float64
 121  assets_3y_pct   26026 non-null  float64
 122  ncfo_3y_pct     24954 non-null  float64
 123  ncf_3y_pct      24892 non-null  float64
 124  equity_3y_pct   26028 non-null  float64
dtypes: float64(117), object(8)
memory usage: 67.4+ MB

<ipython-input-28-4d9dd3b67a66>:2: FutureWarning: null_counts is deprecated. Use show_counts instead
  fundamentals.info(verbose=True, null_counts=True)

In [29]:
#delete instances w/out one year of history
fundamentals = fundamentals[fundamentals['revenue_1y_pct'].notna()]
fundamentals = fundamentals[fundamentals['gp_1y_pct'].notna()]
fundamentals = fundamentals[fundamentals['ebitda_1y_pct'].notna()]
fundamentals = fundamentals[fundamentals['opinc_1y_pct'].notna()]
fundamentals = fundamentals[fundamentals['netinc_1y_pct'].notna()]
fundamentals = fundamentals[fundamentals['eps_1y_pct'].notna()]
fundamentals = fundamentals[fundamentals['assets_1y_pct'].notna()]
fundamentals = fundamentals[fundamentals['ncfo_1y_pct'].notna()]
fundamentals = fundamentals[fundamentals['ncf_1y_pct'].notna()]
fundamentals = fundamentals[fundamentals['equity_1y_pct'].notna()]

In [30]:
#investigate null values
fundamentals.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50923 entries, 4 to 73808
Data columns (total 125 columns):
 #    Column          Non-Null Count  Dtype
---   ------          --------------  -----
 0    ticker          50923 non-null  object
 1    calendardate    50923 non-null  object
 2    accoci          50923 non-null  float64
 3    assets          50923 non-null  float64
 4    assetsavg       50834 non-null  float64
 5    assetsc         39495 non-null  float64
 6    assetsnc        39495 non-null  float64
 7    assetturnover   50834 non-null  float64
 8    bvps            50923 non-null  float64
 9    capex           50922 non-null  float64
 10   cashneq         50923 non-null  float64
 11   cor             50923 non-null  float64
 12   consolinc       50923 non-null  float64
 13   currentratio    39478 non-null  float64
 14   de              50923 non-null  float64
 15   debt            50923 non-null  float64
 16   debtc           39480 non-null  float64
 17   debtnc          39480 non-null  float64
 18   deferredrev     50923 non-null  float64
 19   depamor         50923 non-null  float64
 20   deposits        50923 non-null  float64
 21   dps             50923 non-null  float64
 22   ebit            50923 non-null  float64
 23   ebitda          50923 non-null  float64
 24   ebitdamargin    50626 non-null  float64
 25   ebt             50923 non-null  float64
 26   eps             50923 non-null  float64
 27   epsdil          50809 non-null  float64
 28   equity          50923 non-null  float64
 29   equityavg       50834 non-null  float64
 30   fcf             50922 non-null  float64
 31   fcfps           50922 non-null  float64
 32   gp              50923 non-null  float64
 33   grossmargin     50626 non-null  float64
 34   intangibles     50923 non-null  float64
 35   intexp          50923 non-null  float64
 36   invcap          50923 non-null  float64
 37   invcapavg       50834 non-null  float64
 38   inventory       50923 non-null  float64
 39   investments     50923 non-null  float64
 40   investmentsc    39495 non-null  float64
 41   investmentsnc   39495 non-null  float64
 42   liabilities     50923 non-null  float64
 43   liabilitiesc    39478 non-null  float64
 44   liabilitiesnc   39478 non-null  float64
 45   ncf             50923 non-null  float64
 46   ncfbus          50922 non-null  float64
 47   ncfcommon       50923 non-null  float64
 48   ncfdebt         50923 non-null  float64
 49   ncfdiv          50923 non-null  float64
 50   ncff            50923 non-null  float64
 51   ncfi            50922 non-null  float64
 52   ncfinv          50922 non-null  float64
 53   ncfo            50923 non-null  float64
 54   ncfx            50861 non-null  float64
 55   netinc          50923 non-null  float64
 56   netinccmn       50923 non-null  float64
 57   netincdis       50923 non-null  float64
 58   netincnci       50923 non-null  float64
 59   netmargin       50626 non-null  float64
 60   opex            50923 non-null  float64
 61   opinc           50923 non-null  float64
 62   payables        50923 non-null  float64
 63   payoutratio     50785 non-null  float64
 64   ppnenet         50923 non-null  float64
 65   prefdivis       50923 non-null  float64
 66   ps              50420 non-null  float64
 67   ps1             50420 non-null  float64
 68   receivables     50923 non-null  float64
 69   retearn         49224 non-null  float64
 70   revenue         50923 non-null  float64
 71   rnd             50923 non-null  float64
 72   roa             50834 non-null  float64
 73   roe             50834 non-null  float64
 74   roic            50834 non-null  float64
 75   ros             50626 non-null  float64
 76   sbcomp          50923 non-null  float64
 77   sgna            50923 non-null  float64
 78   sharefactor     50923 non-null  float64
 79   sharesbas       50923 non-null  float64
 80   shareswa        50923 non-null  float64
 81   shareswadil     40808 non-null  float64
 82   sps             50923 non-null  float64
 83   tangibles       50923 non-null  float64
 84   taxassets       50923 non-null  float64
 85   taxexp          50923 non-null  float64
 86   taxliabilities  50923 non-null  float64
 87   tbvps           50923 non-null  float64
 88   workingcapital  39478 non-null  float64
 89   name            50923 non-null  object
 90   exchange        50923 non-null  object
 91   sector          50923 non-null  object
 92   industry        50923 non-null  object
 93   quart           50923 non-null  object
 94   year            50923 non-null  object
 95   revenue_1y_pct  50923 non-null  float64
 96   gp_1y_pct       50923 non-null  float64
 97   ebitda_1y_pct   50923 non-null  float64
 98   opinc_1y_pct    50923 non-null  float64
 99   netinc_1y_pct   50923 non-null  float64
 100  eps_1y_pct      50923 non-null  float64
 101  assets_1y_pct   50923 non-null  float64
 102  ncfo_1y_pct     50923 non-null  float64
 103  ncf_1y_pct      50923 non-null  float64
 104  equity_1y_pct   50923 non-null  float64
 105  revenue_2y_pct  36855 non-null  float64
 106  gp_2y_pct       36856 non-null  float64
 107  ebitda_2y_pct   37102 non-null  float64
 108  opinc_2y_pct    37245 non-null  float64
 109  netinc_2y_pct   37243 non-null  float64
 110  eps_2y_pct      36991 non-null  float64
 111  assets_2y_pct   38344 non-null  float64
 112  ncfo_2y_pct     37099 non-null  float64
 113  ncf_2y_pct      37058 non-null  float64
 114  equity_2y_pct   38344 non-null  float64
 115  revenue_3y_pct  23457 non-null  float64
 116  gp_3y_pct       23458 non-null  float64
 117  ebitda_3y_pct   23733 non-null  float64
 118  opinc_3y_pct    23837 non-null  float64
 119  netinc_3y_pct   23834 non-null  float64
 120  eps_3y_pct      23615 non-null  float64
 121  assets_3y_pct   24635 non-null  float64
 122  ncfo_3y_pct     23730 non-null  float64
 123  ncf_3y_pct      23695 non-null  float64
 124  equity_3y_pct   24635 non-null  float64
dtypes: float64(117), object(8)
memory usage: 49.0+ MB

<ipython-input-30-4d9dd3b67a66>:2: FutureWarning: null_counts is deprecated. Use show_counts instead
  fundamentals.info(verbose=True, null_counts=True)

In [31]:
#where 2 years of history not available, use one year
fundamentals["revenue_2y_pct"] = np.where(fundamentals["revenue_2y_pct"].isnull(), fundamentals["revenue_1y_pct"], fundamentals["revenue_2y_pct"])
fundamentals["gp_2y_pct"] = np.where(fundamentals["gp_2y_pct"].isnull(), fundamentals["gp_1y_pct"], fundamentals["gp_2y_pct"])
fundamentals["ebitda_2y_pct"] = np.where(fundamentals["ebitda_2y_pct"].isnull(), fundamentals["ebitda_1y_pct"], fundamentals["ebitda_2y_pct"])
fundamentals["opinc_2y_pct"] = np.where(fundamentals["opinc_2y_pct"].isnull(), fundamentals["opinc_1y_pct"], fundamentals["opinc_2y_pct"])
fundamentals["netinc_2y_pct"] = np.where(fundamentals["netinc_2y_pct"].isnull(), fundamentals["netinc_1y_pct"], fundamentals["netinc_2y_pct"])
fundamentals["eps_2y_pct"] = np.where(fundamentals["eps_2y_pct"].isnull(), fundamentals["eps_1y_pct"], fundamentals["eps_2y_pct"])
fundamentals["assets_2y_pct"] = np.where(fundamentals["assets_2y_pct"].isnull(), fundamentals["assets_1y_pct"], fundamentals["assets_2y_pct"])
fundamentals["ncfo_2y_pct"] = np.where(fundamentals["ncfo_2y_pct"].isnull(), fundamentals["ncfo_1y_pct"], fundamentals["ncfo_2y_pct"])
fundamentals["ncf_2y_pct"] = np.where(fundamentals["ncf_2y_pct"].isnull(), fundamentals["ncf_1y_pct"], fundamentals["ncf_2y_pct"])
fundamentals["equity_2y_pct"] = np.where(fundamentals["equity_2y_pct"].isnull(), fundamentals["equity_1y_pct"], fundamentals["equity_2y_pct"])

In [32]:
#investigate null values
fundamentals.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50923 entries, 4 to 73808
Data columns (total 125 columns):
 #    Column          Non-Null Count  Dtype
---   ------          --------------  -----
 0    ticker          50923 non-null  object
 1    calendardate    50923 non-null  object
 2    accoci          50923 non-null  float64
 3    assets          50923 non-null  float64
 4    assetsavg       50834 non-null  float64
 5    assetsc         39495 non-null  float64
 6    assetsnc        39495 non-null  float64
 7    assetturnover   50834 non-null  float64
 8    bvps            50923 non-null  float64
 9    capex           50922 non-null  float64
 10   cashneq         50923 non-null  float64
 11   cor             50923 non-null  float64
 12   consolinc       50923 non-null  float64
 13   currentratio    39478 non-null  float64
 14   de              50923 non-null  float64
 15   debt            50923 non-null  float64
 16   debtc           39480 non-null  float64
 17   debtnc          39480 non-null  float64
 18   deferredrev     50923 non-null  float64
 19   depamor         50923 non-null  float64
 20   deposits        50923 non-null  float64
 21   dps             50923 non-null  float64
 22   ebit            50923 non-null  float64
 23   ebitda          50923 non-null  float64
 24   ebitdamargin    50626 non-null  float64
 25   ebt             50923 non-null  float64
 26   eps             50923 non-null  float64
 27   epsdil          50809 non-null  float64
 28   equity          50923 non-null  float64
 29   equityavg       50834 non-null  float64
 30   fcf             50922 non-null  float64
 31   fcfps           50922 non-null  float64
 32   gp              50923 non-null  float64
 33   grossmargin     50626 non-null  float64
 34   intangibles     50923 non-null  float64
 35   intexp          50923 non-null  float64
 36   invcap          50923 non-null  float64
 37   invcapavg       50834 non-null  float64
 38   inventory       50923 non-null  float64
 39   investments     50923 non-null  float64
 40   investmentsc    39495 non-null  float64
 41   investmentsnc   39495 non-null  float64
 42   liabilities     50923 non-null  float64
 43   liabilitiesc    39478 non-null  float64
 44   liabilitiesnc   39478 non-null  float64
 45   ncf             50923 non-null  float64
 46   ncfbus          50922 non-null  float64
 47   ncfcommon       50923 non-null  float64
 48   ncfdebt         50923 non-null  float64
 49   ncfdiv          50923 non-null  float64
 50   ncff            50923 non-null  float64
 51   ncfi            50922 non-null  float64
 52   ncfinv          50922 non-null  float64
 53   ncfo            50923 non-null  float64
 54   ncfx            50861 non-null  float64
 55   netinc          50923 non-null  float64
 56   netinccmn       50923 non-null  float64
 57   netincdis       50923 non-null  float64
 58   netincnci       50923 non-null  float64
 59   netmargin       50626 non-null  float64
 60   opex            50923 non-null  float64
 61   opinc           50923 non-null  float64
 62   payables        50923 non-null  float64
 63   payoutratio     50785 non-null  float64
 64   ppnenet         50923 non-null  float64
 65   prefdivis       50923 non-null  float64
 66   ps              50420 non-null  float64
 67   ps1             50420 non-null  float64
 68   receivables     50923 non-null  float64
 69   retearn         49224 non-null  float64
 70   revenue         50923 non-null  float64
 71   rnd             50923 non-null  float64
 72   roa             50834 non-null  float64
 73   roe             50834 non-null  float64
 74   roic            50834 non-null  float64
 75   ros             50626 non-null  float64
 76   sbcomp          50923 non-null  float64
 77   sgna            50923 non-null  float64
 78   sharefactor     50923 non-null  float64
 79   sharesbas       50923 non-null  float64
 80   shareswa        50923 non-null  float64
 81   shareswadil     40808 non-null  float64
 82   sps             50923 non-null  float64
 83   tangibles       50923 non-null  float64
 84   taxassets       50923 non-null  float64
 85   taxexp          50923 non-null  float64
 86   taxliabilities  50923 non-null  float64
 87   tbvps           50923 non-null  float64
 88   workingcapital  39478 non-null  float64
 89   name            50923 non-null  object
 90   exchange        50923 non-null  object
 91   sector          50923 non-null  object
 92   industry        50923 non-null  object
 93   quart           50923 non-null  object
 94   year            50923 non-null  object
 95   revenue_1y_pct  50923 non-null  float64
 96   gp_1y_pct       50923 non-null  float64
 97   ebitda_1y_pct   50923 non-null  float64
 98   opinc_1y_pct    50923 non-null  float64
 99   netinc_1y_pct   50923 non-null  float64
 100  eps_1y_pct      50923 non-null  float64
 101  assets_1y_pct   50923 non-null  float64
 102  ncfo_1y_pct     50923 non-null  float64
 103  ncf_1y_pct      50923 non-null  float64
 104  equity_1y_pct   50923 non-null  float64
 105  revenue_2y_pct  50923 non-null  float64
 106  gp_2y_pct       50923 non-null  float64
 107  ebitda_2y_pct   50923 non-null  float64
 108  opinc_2y_pct    50923 non-null  float64
 109  netinc_2y_pct   50923 non-null  float64
 110  eps_2y_pct      50923 non-null  float64
 111  assets_2y_pct   50923 non-null  float64
 112  ncfo_2y_pct     50923 non-null  float64
 113  ncf_2y_pct      50923 non-null  float64
 114  equity_2y_pct   50923 non-null  float64
 115  revenue_3y_pct  23457 non-null  float64
 116  gp_3y_pct       23458 non-null  float64
 117  ebitda_3y_pct   23733 non-null  float64
 118  opinc_3y_pct    23837 non-null  float64
 119  netinc_3y_pct   23834 non-null  float64
 120  eps_3y_pct      23615 non-null  float64
 121  assets_3y_pct   24635 non-null  float64
 122  ncfo_3y_pct     23730 non-null  float64
 123  ncf_3y_pct      23695 non-null  float64
 124  equity_3y_pct   24635 non-null  float64
dtypes: float64(117), object(8)
memory usage: 49.0+ MB

<ipython-input-32-4d9dd3b67a66>:2: FutureWarning: null_counts is deprecated. Use show_counts instead
  fundamentals.info(verbose=True, null_counts=True)

In [33]:
#where 3 years of history not available, use average of past two years
fundamentals["revenue_3y_pct"] = np.where(fundamentals["revenue_3y_pct"].isnull(), fundamentals[["revenue_1y_pct", "revenue_2y_pct"]].mean(axis=1), fundamentals["revenue_3y_pct"])
fundamentals["gp_3y_pct"] = np.where(fundamentals["gp_3y_pct"].isnull(), fundamentals[["gp_1y_pct", "gp_2y_pct"]].mean(axis=1), fundamentals["gp_3y_pct"])
fundamentals["ebitda_3y_pct"] = np.where(fundamentals["ebitda_3y_pct"].isnull(), fundamentals[["ebitda_1y_pct","ebitda_2y_pct"]].mean(axis=1), fundamentals["ebitda_3y_pct"])
fundamentals["opinc_3y_pct"] = np.where(fundamentals["opinc_3y_pct"].isnull(), fundamentals[["opinc_1y_pct","opinc_2y_pct"]].mean(axis=1), fundamentals["opinc_3y_pct"])
fundamentals["netinc_3y_pct"] = np.where(fundamentals["netinc_3y_pct"].isnull(), fundamentals[["netinc_1y_pct","netinc_2y_pct"]].mean(axis=1), fundamentals["netinc_3y_pct"])
fundamentals["eps_3y_pct"] = np.where(fundamentals["eps_3y_pct"].isnull(), fundamentals[["eps_1y_pct","eps_2y_pct"]].mean(axis=1), fundamentals["eps_3y_pct"])
fundamentals["assets_3y_pct"] = np.where(fundamentals["assets_3y_pct"].isnull(), fundamentals[["assets_1y_pct","assets_2y_pct"]].mean(axis=1), fundamentals["assets_3y_pct"])
fundamentals["ncfo_3y_pct"] = np.where(fundamentals["ncfo_3y_pct"].isnull(), fundamentals[["ncfo_1y_pct","ncfo_2y_pct"]].mean(axis=1), fundamentals["ncfo_3y_pct"])
fundamentals["ncf_3y_pct"] = np.where(fundamentals["ncf_3y_pct"].isnull(), fundamentals[["ncf_1y_pct","ncf_2y_pct"]].mean(axis=1), fundamentals["ncf_3y_pct"])
fundamentals["equity_3y_pct"] = np.where(fundamentals["equity_3y_pct"].isnull(), fundamentals[["equity_1y_pct","equity_2y_pct"]].mean(axis=1), fundamentals["equity_3y_pct"])

In [34]:
#investigate null values
fundamentals.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50923 entries, 4 to 73808
Data columns (total 125 columns):
 #    Column          Non-Null Count  Dtype
---   ------          --------------  -----
 0    ticker          50923 non-null  object
 1    calendardate    50923 non-null  object
 2    accoci          50923 non-null  float64
 3    assets          50923 non-null  float64
 4    assetsavg       50834 non-null  float64
 5    assetsc         39495 non-null  float64
 6    assetsnc        39495 non-null  float64
 7    assetturnover   50834 non-null  float64
 8    bvps            50923 non-null  float64
 9    capex           50922 non-null  float64
 10   cashneq         50923 non-null  float64
 11   cor             50923 non-null  float64
 12   consolinc       50923 non-null  float64
 13   currentratio    39478 non-null  float64
 14   de              50923 non-null  float64
 15   debt            50923 non-null  float64
 16   debtc           39480 non-null  float64
 17   debtnc          39480 non-null  float64
 18   deferredrev     50923 non-null  float64
 19   depamor         50923 non-null  float64
 20   deposits        50923 non-null  float64
 21   dps             50923 non-null  float64
 22   ebit            50923 non-null  float64
 23   ebitda          50923 non-null  float64
 24   ebitdamargin    50626 non-null  float64
 25   ebt             50923 non-null  float64
 26   eps             50923 non-null  float64
 27   epsdil          50809 non-null  float64
 28   equity          50923 non-null  float64
 29   equityavg       50834 non-null  float64
 30   fcf             50922 non-null  float64
 31   fcfps           50922 non-null  float64
 32   gp              50923 non-null  float64
 33   grossmargin     50626 non-null  float64
 34   intangibles     50923 non-null  float64
 35   intexp          50923 non-null  float64
 36   invcap          50923 non-null  float64
 37   invcapavg       50834 non-null  float64
 38   inventory       50923 non-null  float64
 39   investments     50923 non-null  float64
 40   investmentsc    39495 non-null  float64
 41   investmentsnc   39495 non-null  float64
 42   liabilities     50923 non-null  float64
 43   liabilitiesc    39478 non-null  float64
 44   liabilitiesnc   39478 non-null  float64
 45   ncf             50923 non-null  float64
 46   ncfbus          50922 non-null  float64
 47   ncfcommon       50923 non-null  float64
 48   ncfdebt         50923 non-null  float64
 49   ncfdiv          50923 non-null  float64
 50   ncff            50923 non-null  float64
 51   ncfi            50922 non-null  float64
 52   ncfinv          50922 non-null  float64
 53   ncfo            50923 non-null  float64
 54   ncfx            50861 non-null  float64
 55   netinc          50923 non-null  float64
 56   netinccmn       50923 non-null  float64
 57   netincdis       50923 non-null  float64
 58   netincnci       50923 non-null  float64
 59   netmargin       50626 non-null  float64
 60   opex            50923 non-null  float64
 61   opinc           50923 non-null  float64
 62   payables        50923 non-null  float64
 63   payoutratio     50785 non-null  float64
 64   ppnenet         50923 non-null  float64
 65   prefdivis       50923 non-null  float64
 66   ps              50420 non-null  float64
 67   ps1             50420 non-null  float64
 68   receivables     50923 non-null  float64
 69   retearn         49224 non-null  float64
 70   revenue         50923 non-null  float64
 71   rnd             50923 non-null  float64
 72   roa             50834 non-null  float64
 73   roe             50834 non-null  float64
 74   roic            50834 non-null  float64
 75   ros             50626 non-null  float64
 76   sbcomp          50923 non-null  float64
 77   sgna            50923 non-null  float64
 78   sharefactor     50923 non-null  float64
 79   sharesbas       50923 non-null  float64
 80   shareswa        50923 non-null  float64
 81   shareswadil     40808 non-null  float64
 82   sps             50923 non-null  float64
 83   tangibles       50923 non-null  float64
 84   taxassets       50923 non-null  float64
 85   taxexp          50923 non-null  float64
 86   taxliabilities  50923 non-null  float64
 87   tbvps           50923 non-null  float64
 88   workingcapital  39478 non-null  float64
 89   name            50923 non-null  object
 90   exchange        50923 non-null  object
 91   sector          50923 non-null  object
 92   industry        50923 non-null  object
 93   quart           50923 non-null  object
 94   year            50923 non-null  object
 95   revenue_1y_pct  50923 non-null  float64
 96   gp_1y_pct       50923 non-null  float64
 97   ebitda_1y_pct   50923 non-null  float64
 98   opinc_1y_pct    50923 non-null  float64
 99   netinc_1y_pct   50923 non-null  float64
 100  eps_1y_pct      50923 non-null  float64
 101  assets_1y_pct   50923 non-null  float64
 102  ncfo_1y_pct     50923 non-null  float64
 103  ncf_1y_pct      50923 non-null  float64
 104  equity_1y_pct   50923 non-null  float64
 105  revenue_2y_pct  50923 non-null  float64
 106  gp_2y_pct       50923 non-null  float64
 107  ebitda_2y_pct   50923 non-null  float64
 108  opinc_2y_pct    50923 non-null  float64
 109  netinc_2y_pct   50923 non-null  float64
 110  eps_2y_pct      50923 non-null  float64
 111  assets_2y_pct   50923 non-null  float64
 112  ncfo_2y_pct     50923 non-null  float64
 113  ncf_2y_pct      50923 non-null  float64
 114  equity_2y_pct   50923 non-null  float64
 115  revenue_3y_pct  50923 non-null  float64
 116  gp_3y_pct       50923 non-null  float64
 117  ebitda_3y_pct   50923 non-null  float64
 118  opinc_3y_pct    50923 non-null  float64
 119  netinc_3y_pct   50923 non-null  float64
 120  eps_3y_pct      50923 non-null  float64
 121  assets_3y_pct   50923 non-null  float64
 122  ncfo_3y_pct     50923 non-null  float64
 123  ncf_3y_pct      50923 non-null  float64
 124  equity_3y_pct   50923 non-null  float64
dtypes: float64(117), object(8)
memory usage: 49.0+ MB

<ipython-input-34-4d9dd3b67a66>:2: FutureWarning: null_counts is deprecated. Use show_counts instead
  fundamentals.info(verbose=True, null_counts=True)

In [35]:
#replace remaining null values with zero
fundamentals.fillna(0, inplace=True)

In [36]:
#investigate null values
fundamentals.info(verbose=True, null_counts=True)

<ipython-input-36-4d9dd3b67a66>:2: FutureWarning: null_counts is deprecated. Use show_counts instead
  fundamentals.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50923 entries, 4 to 73808
Data columns (total 125 columns):
 #    Column          Non-Null Count  Dtype
---   ------          --------------  -----
 0    ticker          50923 non-null  object
 1    calendardate    50923 non-null  object
 2    accoci          50923 non-null  float64
 3    assets          50923 non-null  float64
 4    assetsavg       50923 non-null  float64
 5    assetsc         50923 non-null  float64
 6    assetsnc        50923 non-null  float64
 7    assetturnover   50923 non-null  float64
 8    bvps            50923 non-null  float64
 9    capex           50923 non-null  float64
 10   cashneq         50923 non-null  float64
 11   cor             50923 non-null  float64
 12   consolinc       50923 non-null  float64
 13   currentratio    50923 non-null  float64
 14   de              50923 non-null  float64
 15   debt            50923 non-null  float64
 16   debtc           50923 non-null  float64
 17   debtnc          50923 non-null  float64
 18   deferredrev     50923 non-null  float64
 19   depamor         50923 non-null  float64
 20   deposits        50923 non-null  float64
 21   dps             50923 non-null  float64
 22   ebit            50923 non-null  float64
 23   ebitda          50923 non-null  float64
 24   ebitdamargin    50923 non-null  float64
 25   ebt             50923 non-null  float64
 26   eps             50923 non-null  float64
 27   epsdil          50923 non-null  float64
 28   equity          50923 non-null  float64
 29   equityavg       50923 non-null  float64
 30   fcf             50923 non-null  float64
 31   fcfps           50923 non-null  float64
 32   gp              50923 non-null  float64
 33   grossmargin     50923 non-null  float64
 34   intangibles     50923 non-null  float64
 35   intexp          50923 non-null  float64
 36   invcap          50923 non-null  float64
 37   invcapavg       50923 non-null  float64
 38   inventory       50923 non-null  float64
 39   investments     50923 non-null  float64
 40   investmentsc    50923 non-null  float64
 41   investmentsnc   50923 non-null  float64
 42   liabilities     50923 non-null  float64
 43   liabilitiesc    50923 non-null  float64
 44   liabilitiesnc   50923 non-null  float64
 45   ncf             50923 non-null  float64
 46   ncfbus          50923 non-null  float64
 47   ncfcommon       50923 non-null  float64
 48   ncfdebt         50923 non-null  float64
 49   ncfdiv          50923 non-null  float64
 50   ncff            50923 non-null  float64
 51   ncfi            50923 non-null  float64
 52   ncfinv          50923 non-null  float64
 53   ncfo            50923 non-null  float64
 54   ncfx            50923 non-null  float64
 55   netinc          50923 non-null  float64
 56   netinccmn       50923 non-null  float64
 57   netincdis       50923 non-null  float64
 58   netincnci       50923 non-null  float64
 59   netmargin       50923 non-null  float64
 60   opex            50923 non-null  float64
 61   opinc           50923 non-null  float64
 62   payables        50923 non-null  float64
 63   payoutratio     50923 non-null  float64
 64   ppnenet         50923 non-null  float64
 65   prefdivis       50923 non-null  float64
 66   ps              50923 non-null  float64
 67   ps1             50923 non-null  float64
 68   receivables     50923 non-null  float64
 69   retearn         50923 non-null  float64
 70   revenue         50923 non-null  float64
 71   rnd             50923 non-null  float64
 72   roa             50923 non-null  float64
 73   roe             50923 non-null  float64
 74   roic            50923 non-null  float64
 75   ros             50923 non-null  float64
 76   sbcomp          50923 non-null  float64
 77   sgna            50923 non-null  float64
 78   sharefactor     50923 non-null  float64
 79   sharesbas       50923 non-null  float64
 80   shareswa        50923 non-null  float64
 81   shareswadil     50923 non-null  float64
 82   sps             50923 non-null  float64
 83   tangibles       50923 non-null  float64
 84   taxassets       50923 non-null  float64
 85   taxexp          50923 non-null  float64
 86   taxliabilities  50923 non-null  float64
 87   tbvps           50923 non-null  float64
 88   workingcapital  50923 non-null  float64
 89   name            50923 non-null  object
 90   exchange        50923 non-null  object
 91   sector          50923 non-null  object
 92   industry        50923 non-null  object
 93   quart           50923 non-null  object
 94   year            50923 non-null  object
 95   revenue_1y_pct  50923 non-null  float64
 96   gp_1y_pct       50923 non-null  float64
 97   ebitda_1y_pct   50923 non-null  float64
 98   opinc_1y_pct    50923 non-null  float64
 99   netinc_1y_pct   50923 non-null  float64
 100  eps_1y_pct      50923 non-null  float64
 101  assets_1y_pct   50923 non-null  float64
 102  ncfo_1y_pct     50923 non-null  float64
 103  ncf_1y_pct      50923 non-null  float64
 104  equity_1y_pct   50923 non-null  float64
 105  revenue_2y_pct  50923 non-null  float64
 106  gp_2y_pct       50923 non-null  float64
 107  ebitda_2y_pct   50923 non-null  float64
 108  opinc_2y_pct    50923 non-null  float64
 109  netinc_2y_pct   50923 non-null  float64
 110  eps_2y_pct      50923 non-null  float64
 111  assets_2y_pct   50923 non-null  float64
 112  ncfo_2y_pct     50923 non-null  float64
 113  ncf_2y_pct      50923 non-null  float64
 114  equity_2y_pct   50923 non-null  float64
 115  revenue_3y_pct  50923 non-null  float64
 116  gp_3y_pct       50923 non-null  float64
 117  ebitda_3y_pct   50923 non-null  float64
 118  opinc_3y_pct    50923 non-null  float64
 119  netinc_3y_pct   50923 non-null  float64
 120  eps_3y_pct      50923 non-null  float64
 121  assets_3y_pct   50923 non-null  float64
 122  ncfo_3y_pct     50923 non-null  float64
 123  ncf_3y_pct      50923 non-null  float64
 124  equity_3y_pct   50923 non-null  float64
dtypes: float64(117), object(8)
memory usage: 49.0+ MB

### Import Price Data

In [36]:
from datetime import date, timedelta

sdate = date(1997, 1, 1)   # start date
edate = date(2021, 3, 1)   # end date

delta = edate - sdate       # as timedelta

days =[]

for i in range(delta.days + 1):
    day = str(sdate + timedelta(days=i))
    days.append(day)

In [130]:
dates = ", ".join(days)

In [131]:
prices = pd.DataFrame()

In [132]:
for tick in ticks:
    tick_var = quandl.get_table('SHARADAR/SEP', date=dates, ticker=tick)
    prices = prices.append(tick_var)
    del tick_var

In [134]:
prices.to_pickle("prices.pkl")

In [58]:
prices_1 = pd.read_pickle("prices.pkl")

In [59]:
prices_2 = pd.read_pickle("prices_2.pkl")

In [60]:
prices_3 = pd.read_pickle("prices_3.pkl")

In [61]:
prices_4 = pd.read_pickle("prices_4.pkl")

In [62]:
daily_prices = prices_1.append(prices_2).append(prices_3).append(prices_4)

In [63]:
daily_prices.reset_index(inplace=True)

In [64]:
del daily_prices["None"]

In [65]:
def calendar_date(date):
    str_date = str(date)
    str_yr_mo_d = str_date.split(" ")[0].split("-")
    yr_mo_d = [int(i) for i in str_yr_mo_d]
    year = yr_mo_d[0]
    if yr_mo_d[1] <= 3:
        return str(year-1) + "-12-31"
    elif yr_mo_d[1] <= 6 and yr_mo_d[1] > 3:
        return str(year) + "-03-31"
    elif yr_mo_d[1] <= 9 and yr_mo_d[1] > 6:
        return str(year) + "-06-30"
    else:
        return str(year) + "-09-30"

In [66]:
daily_prices["calendardate"] = daily_prices.date.apply(calendar_date)

In [67]:
daily_prices

,ticker,date,open,high,low,close,volume,dividends,closeunadj,lastupdated,calendardate
0,A,2021-03-01,123.05,125.150,122.880,124.48,1404367.0,0.0,124.48,2021-03-01,2020-12-31
1,A,2021-02-26,122.93,123.509,120.645,122.07,1909664.0,0.0,122.07,2021-02-26,2020-12-31
2,A,2021-02-25,124.81,125.250,121.930,122.10,1430936.0,0.0,122.10,2021-02-25,2020-12-31
3,A,2021-02-24,122.26,125.410,122.010,125.02,1898360.0,0.0,125.02,2021-02-24,2020-12-31
4,A,2021-02-23,123.51,123.510,120.410,122.42,2124665.0,0.0,122.42,2021-02-23,2020-12-31
...,...,...,...,...,...,...,...,...,...,...,...
12703610,HUDI,2021-01-28,6.19,6.286,6.020,6.09,64794.0,0.0,6.09,2021-01-28,2020-12-31
12703611,HUDI,2021-01-27,6.54,6.550,6.170,6.31,101876.0,0.0,6.31,2021-01-27,2020-12-31
12703612,HUDI,2021-01-26,6.30,6.610,6.110,6.61,189937.0,0.0,6.61,2021-01-26,2020-12-31
12703613,HUDI,2021-01-25,6.79,6.920,5.790,6.15,523176.0,0.0,6.15,2021-01-25,2020-12-31
12703614,HUDI,2021-01-22,9.01,9.920,6.620,7.13,1472034.0,0.0,7.13,2021-01-22,2020-12-31

In [68]:
daily_prices.to_pickle("daily_prices.pkl")

In [37]:
daily_prices = pd.read_pickle("daily_prices.pkl")

In [38]:
daily_prices = daily_prices[["ticker", "date", "close", "volume", "calendardate"]]

In [39]:
daily_prices

         ticker       date   close     volume calendardate
0             A 2021-03-01  124.48  1404367.0   2020-12-31
1             A 2021-02-26  122.07  1909664.0   2020-12-31
2             A 2021-02-25  122.10  1430936.0   2020-12-31
3             A 2021-02-24  125.02  1898360.0   2020-12-31
4             A 2021-02-23  122.42  2124665.0   2020-12-31
...         ...        ...     ...        ...          ...
12703610   HUDI 2021-01-28    6.09    64794.0   2020-12-31
12703611   HUDI 2021-01-27    6.31   101876.0   2020-12-31
12703612   HUDI 2021-01-26    6.61   189937.0   2020-12-31
12703613   HUDI 2021-01-25    6.15   523176.0   2020-12-31
12703614   HUDI 2021-01-22    7.13  1472034.0   2020-12-31

[12703615 rows x 5 columns]

In [40]:
daily_prices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12703615 entries, 0 to 12703614
Data columns (total 5 columns):
 #   Column        Dtype
---  ------        -----
 0   ticker        object
 1   date          datetime64[ns]
 2   close         float64
 3   volume        float64
 4   calendardate  object
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 484.6+ MB

### Merge Prices and Fundamentals

In [41]:
prices_fundamentals = pd.merge(daily_prices, fundamentals, on=["calendardate", "ticker"])

In [42]:
prices_fundamentals

,ticker,date,close,volume,calendardate,accoci,assets,assetsavg,assetsc,assetsnc,...,revenue_3y_pct,gp_3y_pct,ebitda_3y_pct,opinc_3y_pct,netinc_3y_pct,eps_3y_pct,assets_3y_pct,ncfo_3y_pct,ncf_3y_pct,equity_3y_pct
0,A,2021-03-01,124.480,1404367.0,2020-12-31,-469000000.0,9.674000e+09,9.575500e+09,3.483000e+09,6.191000e+09,...,0.198007,0.177033,0.165487,0.097254,3.132653,3.241935,0.11221,0.232794,-0.826087,0.062362
1,A,2021-02-26,122.070,1909664.0,2020-12-31,-469000000.0,9.674000e+09,9.575500e+09,3.483000e+09,6.191000e+09,...,0.198007,0.177033,0.165487,0.097254,3.132653,3.241935,0.11221,0.232794,-0.826087,0.062362
2,A,2021-02-25,122.100,1430936.0,2020-12-31,-469000000.0,9.674000e+09,9.575500e+09,3.483000e+09,6.191000e+09,...,0.198007,0.177033,0.165487,0.097254,3.132653,3.241935,0.11221,0.232794,-0.826087,0.062362
3,A,2021-02-24,125.020,1898360.0,2020-12-31,-469000000.0,9.674000e+09,9.575500e+09,3.483000e+09,6.191000e+09,...,0.198007,0.177033,0.165487,0.097254,3.132653,3.241935,0.11221,0.232794,-0.826087,0.062362
4,A,2021-02-23,122.420,2124665.0,2020-12-31,-469000000.0,9.674000e+09,9.575500e+09,3.483000e+09,6.191000e+09,...,0.198007,0.177033,0.165487,0.097254,3.132653,3.241935,0.11221,0.232794,-0.826087,0.062362
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3120609,HIMS,2020-10-05,10.330,1094159.0,2020-09-30,-10000.0,1.191870e+08,2.057668e+08,1.071310e+08,1.205600e+07,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
3120610,HIMS,2020-10-02,10.512,1570850.0,2020-09-30,0.0,2.058140e+08,2.057668e+08,1.332751e+06,2.044812e+08,...,-1.000000,-1.000000,-0.975185,-0.725694,-0.976828,-1.923077,0.36762,-0.727232,-1.036540,-0.517441
3120611,HIMS,2020-10-02,10.512,1570850.0,2020-09-30,-10000.0,1.191870e+08,2.057668e+08,1.071310e+08,1.205600e+07,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
3120612,HIMS,2020-10-01,10.800,5090233.0,2020-09-30,0.0,2.058140e+08,2.057668e+08,1.332751e+06,2.044812e+08,...,-1.000000,-1.000000,-0.975185,-0.725694,-0.976828,-1.923077,0.36762,-0.727232,-1.036540,-0.517441
3120613,HIMS,2020-10-01,10.800,5090233.0,2020-09-30,-10000.0,1.191870e+08,2.057668e+08,1.071310e+08,1.205600e+07,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000

In [43]:
prices_fundamentals = prices_fundamentals.sort_values(['ticker'], ascending=True) \
        .groupby(['ticker'], sort=False) \
        .apply(lambda x: x.sort_values(['date'], ascending=True)) \
        .reset_index(drop=True)

In [44]:
prices_fundamentals["volume_change"] = prices_fundamentals.groupby("ticker")["volume"].apply(pd.Series.pct_change)

In [45]:
prices_fundamentals["price_change"] = prices_fundamentals.groupby("ticker")["close"].apply(pd.Series.pct_change)

In [46]:
prices_fundamentals = prices_fundamentals[prices_fundamentals.price_change.notna()]

In [47]:
prices_fundamentals = prices_fundamentals[prices_fundamentals.volume_change.notna()]

In [48]:
daily_sector_price_change = pd.DataFrame(prices_fundamentals.groupby(["date", "sector"])["price_change"].mean()).reset_index()
daily_sector_price_change

            date              sector  price_change
0     2016-04-04   Consumer Cyclical     -0.006746
1     2016-04-04  Consumer Defensive     -0.016885
2     2016-04-04  Financial Services      0.011933
3     2016-04-04          Healthcare      0.024000
4     2016-04-04         Industrials     -0.017285
...          ...                 ...           ...
13006 2021-03-01          Healthcare      0.026588
13007 2021-03-01         Industrials      0.030260
13008 2021-03-01         Real Estate      0.012079
13009 2021-03-01          Technology      0.036234
13010 2021-03-01           Utilities      0.017842

[13011 rows x 3 columns]

In [49]:
prices_fundamentals = pd.merge(prices_fundamentals, daily_sector_price_change, how="left", on=["date", "sector"])

In [50]:
prices_fundamentals.rename(columns = {"price_change_x":"price_change", "price_change_y":"price_change_sector"}, inplace=True)

In [51]:
prices_fundamentals["price_change_norm_sector"] = prices_fundamentals["price_change"] - prices_fundamentals["price_change_sector"]
prices_fundamentals

,ticker,date,close,volume,calendardate,accoci,assets,assetsavg,assetsc,assetsnc,...,netinc_3y_pct,eps_3y_pct,assets_3y_pct,ncfo_3y_pct,ncf_3y_pct,equity_3y_pct,volume_change,price_change,price_change_sector,price_change_norm_sector
0,A,2017-04-04,52.62,2017094.0,2017-03-31,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,4.216000e+09,...,0.265217,0.294964,0.049215,0.171512,-1.052497,0.050457,0.301160,-0.010902,-0.012133,0.001231
1,A,2017-04-05,52.71,1778251.0,2017-03-31,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,4.216000e+09,...,0.265217,0.294964,0.049215,0.171512,-1.052497,0.050457,-0.118409,0.001710,-0.018951,0.020661
2,A,2017-04-06,53.15,1548170.0,2017-03-31,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,4.216000e+09,...,0.265217,0.294964,0.049215,0.171512,-1.052497,0.050457,-0.129386,0.008348,0.003168,0.005179
3,A,2017-04-07,52.84,1243550.0,2017-03-31,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,4.216000e+09,...,0.265217,0.294964,0.049215,0.171512,-1.052497,0.050457,-0.196761,-0.005833,-0.000537,-0.005296
4,A,2017-04-10,52.72,1025248.0,2017-03-31,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,4.216000e+09,...,0.265217,0.294964,0.049215,0.171512,-1.052497,0.050457,-0.175547,-0.002271,-0.001594,-0.000677
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3112076,ZYXI,2021-02-23,18.07,646106.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.232043,0.173913,7.083212,-0.900969,3.726025,10.391505,0.243751,-0.049947,-0.022485,-0.027463
3112077,ZYXI,2021-02-24,18.42,315802.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.232043,0.173913,7.083212,-0.900969,3.726025,10.391505,-0.511223,0.019369,0.019750,-0.000381
3112078,ZYXI,2021-02-25,17.42,388872.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.232043,0.173913,7.083212,-0.900969,3.726025,10.391505,0.231379,-0.054289,-0.031866,-0.022423
3112079,ZYXI,2021-02-26,14.52,2337972.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.232043,0.173913,7.083212,-0.900969,3.726025,10.391505,5.012189,-0.166475,-0.002791,-0.163684
3112080,ZYXI,2021-03-01,14.69,1244001.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.232043,0.173913,7.083212,-0.900969,3.726025,10.391505,-0.467915,0.011708,0.026588,-0.014880

In [52]:
daily_industry_price_change = pd.DataFrame(prices_fundamentals.groupby(["date", "industry"])["price_change"].mean()).reset_index()
daily_industry_price_change

             date                        industry  price_change
0      2016-04-04                  Apparel Retail      0.000171
1      2016-04-04         Communication Equipment     -0.024254
2      2016-04-04             Consulting Services     -0.003207
3      2016-04-04                 Credit Services      0.011933
4      2016-04-04          Diagnostics & Research      0.024000
...           ...                             ...           ...
160537 2021-03-01  Utilities - Regulated Electric      0.018646
160538 2021-03-01       Utilities - Regulated Gas      0.015385
160539 2021-03-01     Utilities - Regulated Water      0.012992
160540 2021-03-01           Utilities - Renewable      0.022274
160541 2021-03-01                Waste Management      0.030494

[160542 rows x 3 columns]

In [54]:
prices_fundamentals = pd.merge(prices_fundamentals, daily_industry_price_change, how="left", on=["date", "industry"])

In [56]:
prices_fundamentals.rename(columns = {"price_change_x":"price_change", "price_change_y":"price_change_industry"}, inplace=True)

In [57]:
prices_fundamentals["price_change_norm_industry"] = prices_fundamentals["price_change"] - prices_fundamentals["price_change_industry"]
prices_fundamentals

,ticker,date,close,volume,calendardate,accoci,assets,assetsavg,assetsc,assetsnc,...,assets_3y_pct,ncfo_3y_pct,ncf_3y_pct,equity_3y_pct,volume_change,price_change,price_change_sector,price_change_norm_sector,price_change_industry,price_change_norm_industry
0,A,2017-04-04,52.62,2017094.0,2017-03-31,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,4.216000e+09,...,0.049215,0.171512,-1.052497,0.050457,0.301160,-0.010902,-0.012133,0.001231,-0.013175,0.002273
1,A,2017-04-05,52.71,1778251.0,2017-03-31,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,4.216000e+09,...,0.049215,0.171512,-1.052497,0.050457,-0.118409,0.001710,-0.018951,0.020661,-0.019604,0.021315
2,A,2017-04-06,53.15,1548170.0,2017-03-31,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,4.216000e+09,...,0.049215,0.171512,-1.052497,0.050457,-0.129386,0.008348,0.003168,0.005179,0.012463,-0.004116
3,A,2017-04-07,52.84,1243550.0,2017-03-31,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,4.216000e+09,...,0.049215,0.171512,-1.052497,0.050457,-0.196761,-0.005833,-0.000537,-0.005296,-0.001967,-0.003866
4,A,2017-04-10,52.72,1025248.0,2017-03-31,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,4.216000e+09,...,0.049215,0.171512,-1.052497,0.050457,-0.175547,-0.002271,-0.001594,-0.000677,-0.002827,0.000556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3112076,ZYXI,2021-02-23,18.07,646106.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,7.083212,-0.900969,3.726025,10.391505,0.243751,-0.049947,-0.022485,-0.027463,-0.021961,-0.027987
3112077,ZYXI,2021-02-24,18.42,315802.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,7.083212,-0.900969,3.726025,10.391505,-0.511223,0.019369,0.019750,-0.000381,0.015422,0.003947
3112078,ZYXI,2021-02-25,17.42,388872.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,7.083212,-0.900969,3.726025,10.391505,0.231379,-0.054289,-0.031866,-0.022423,-0.021537,-0.032751
3112079,ZYXI,2021-02-26,14.52,2337972.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,7.083212,-0.900969,3.726025,10.391505,5.012189,-0.166475,-0.002791,-0.163684,0.015404,-0.181879
3112080,ZYXI,2021-03-01,14.69,1244001.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,7.083212,-0.900969,3.726025,10.391505,-0.467915,0.011708,0.026588,-0.014880,0.034998,-0.023290

### Rolling Averages: Price/Volume/Price_Change/Volume_Change

In [60]:
prices_fundamentals["price_weekly_avg"] = prices_fundamentals.groupby("ticker")["close"].rolling(5).mean().reset_index(0,drop=True)
prices_fundamentals["price_month_avg"] = prices_fundamentals.groupby("ticker")["close"].rolling(21).mean().reset_index(0,drop=True)
prices_fundamentals["price_quarter_avg"] = prices_fundamentals.groupby("ticker")["close"].rolling(63).mean().reset_index(0,drop=True)
prices_fundamentals["price_semi_annual_avg"] = prices_fundamentals.groupby("ticker")["close"].rolling(126).mean().reset_index(0,drop=True)
prices_fundamentals["price_annual_avg"] = prices_fundamentals.groupby("ticker")["close"].rolling(253).mean().reset_index(0,drop=True)
prices_fundamentals["price_two_year_avg"] = prices_fundamentals.groupby("ticker")["close"].rolling(506).mean().reset_index(0,drop=True)
prices_fundamentals["price_three_year_avg"] = prices_fundamentals.groupby("ticker")["close"].rolling(759).mean().reset_index(0,drop=True)
prices_fundamentals

,ticker,date,close,volume,calendardate,accoci,assets,assetsavg,assetsc,assetsnc,...,price_change_norm_sector,price_change_industry,price_change_norm_industry,price_weekly_avg,price_month_avg,price_quarter_avg,price_semi_annual_avg,price_annual_avg,price_two_year_avg,price_three_year_avg
0,A,2017-04-04,52.62,2017094.0,2017-03-31,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,4.216000e+09,...,0.001231,-0.013175,0.002273,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A,2017-04-05,52.71,1778251.0,2017-03-31,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,4.216000e+09,...,0.020661,-0.019604,0.021315,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A,2017-04-06,53.15,1548170.0,2017-03-31,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,4.216000e+09,...,0.005179,0.012463,-0.004116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A,2017-04-07,52.84,1243550.0,2017-03-31,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,4.216000e+09,...,-0.005296,-0.001967,-0.003866,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A,2017-04-10,52.72,1025248.0,2017-03-31,-477000000.0,8.016000e+09,7.856000e+09,3.800000e+09,4.216000e+09,...,-0.000677,-0.002827,0.000556,52.808,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3112076,ZYXI,2021-02-23,18.07,646106.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,-0.027463,-0.021961,-0.027987,18.052,18.970000,15.830794,15.560516,16.582016,12.486292,9.382418
3112077,ZYXI,2021-02-24,18.42,315802.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,-0.000381,0.015422,0.003947,18.138,18.960000,15.910159,15.584563,16.602016,12.512024,9.402655
3112078,ZYXI,2021-02-25,17.42,388872.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,-0.022423,-0.021537,-0.032751,18.160,18.889524,15.970476,15.598532,16.620593,12.535727,9.421653
3112079,ZYXI,2021-02-26,14.52,2337972.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,-0.163684,0.015404,-0.181879,17.490,18.547143,15.987619,15.589802,16.628063,12.553415,9.436831
3112080,ZYXI,2021-03-01,14.69,1244001.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,-0.014880,0.034998,-0.023290,16.624,18.280476,16.007778,15.586786,16.639012,12.571775,9.452181

In [61]:
#delete instances w/ < semi-annual year of history
prices_fundamentals = prices_fundamentals[prices_fundamentals['price_weekly_avg'].notna()]
prices_fundamentals = prices_fundamentals[prices_fundamentals['price_month_avg'].notna()]
prices_fundamentals = prices_fundamentals[prices_fundamentals['price_quarter_avg'].notna()]

In [62]:
#use closest available price average
prices_fundamentals["price_semi_annual_avg"] = np.where(prices_fundamentals["price_semi_annual_avg"].isnull(), prices_fundamentals["price_quarter_avg"], prices_fundamentals["price_semi_annual_avg"])
prices_fundamentals["price_annual_avg"] = np.where(prices_fundamentals["price_annual_avg"].isnull(), prices_fundamentals["price_semi_annual_avg"], prices_fundamentals["price_annual_avg"])
prices_fundamentals["price_two_year_avg"] = np.where(prices_fundamentals["price_two_year_avg"].isnull(), prices_fundamentals["price_annual_avg"], prices_fundamentals["price_two_year_avg"])
prices_fundamentals["price_three_year_avg"] = np.where(prices_fundamentals["price_three_year_avg"].isnull(), prices_fundamentals["price_two_year_avg"], prices_fundamentals["price_three_year_avg"])

In [63]:
prices_fundamentals["volume_weekly_avg"] = prices_fundamentals.groupby("ticker")["volume"].rolling(window=5).mean().reset_index(0,drop=True)
prices_fundamentals["volume_month_avg"] = prices_fundamentals.groupby("ticker")["volume"].rolling(window=21).mean().reset_index(0,drop=True)
prices_fundamentals["volume_quarter_avg"] = prices_fundamentals.groupby("ticker")["volume"].rolling(window=63).mean().reset_index(0,drop=True)
prices_fundamentals["volume_semi_annual_avg"] = prices_fundamentals.groupby("ticker")["volume"].rolling(window=126).mean().reset_index(0,drop=True)
prices_fundamentals["volume_annual_avg"] = prices_fundamentals.groupby("ticker")["volume"].rolling(window=253).mean().reset_index(0,drop=True)
prices_fundamentals["volume_two_year_avg"] = prices_fundamentals.groupby("ticker")["volume"].rolling(window=506).mean().reset_index(0,drop=True)
prices_fundamentals["volume_three_year_avg"] = prices_fundamentals.groupby("ticker")["volume"].rolling(window=759).mean().reset_index(0,drop=True)
prices_fundamentals

,ticker,date,close,volume,calendardate,accoci,assets,assetsavg,assetsc,assetsnc,...,price_annual_avg,price_two_year_avg,price_three_year_avg,volume_weekly_avg,volume_month_avg,volume_quarter_avg,volume_semi_annual_avg,volume_annual_avg,volume_two_year_avg,volume_three_year_avg
62,A,2017-07-03,59.13,1489574.0,2017-06-30,-417000000.0,8.261000e+09,7.987750e+09,3.996000e+09,4.265000e+09,...,57.052857,57.052857,57.052857,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,A,2017-07-05,59.77,1638980.0,2017-06-30,-417000000.0,8.261000e+09,7.987750e+09,3.996000e+09,4.265000e+09,...,57.166349,57.166349,57.166349,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,A,2017-07-06,59.22,2249516.0,2017-06-30,-417000000.0,8.261000e+09,7.987750e+09,3.996000e+09,4.265000e+09,...,57.269683,57.269683,57.269683,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,A,2017-07-07,59.63,965439.0,2017-06-30,-417000000.0,8.261000e+09,7.987750e+09,3.996000e+09,4.265000e+09,...,57.372540,57.372540,57.372540,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,A,2017-07-10,59.86,1146033.0,2017-06-30,-417000000.0,8.261000e+09,7.987750e+09,3.996000e+09,4.265000e+09,...,57.483968,57.483968,57.483968,1497908.4,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3112076,ZYXI,2021-02-23,18.07,646106.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,16.582016,12.486292,9.382418,461351.8,619621.761905,553335.920635,664015.277778,802095.774704,539367.227273,368729.075099
3112077,ZYXI,2021-02-24,18.42,315802.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,16.602016,12.512024,9.402655,432811.4,592066.190476,551276.777778,660963.976190,798563.675889,539816.966403,369107.865613
3112078,ZYXI,2021-02-25,17.42,388872.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,16.620593,12.535727,9.421653,425765.8,574050.380952,552075.253968,656643.198413,798216.023715,540437.000000,369561.320158
3112079,ZYXI,2021-02-26,14.52,2337972.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,16.628063,12.553415,9.436831,841646.8,588294.095238,582528.920635,671895.515873,806417.588933,544881.749012,372614.511199
3112080,ZYXI,2021-03-01,14.69,1244001.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,16.639012,12.571775,9.452181,986550.6,593610.333333,597346.476190,675071.904762,809966.470356,547245.525692,374224.789196

In [64]:
#delete instances w/ < semi-annual year of history
prices_fundamentals = prices_fundamentals[prices_fundamentals['volume_weekly_avg'].notna()]
prices_fundamentals = prices_fundamentals[prices_fundamentals['volume_month_avg'].notna()]
prices_fundamentals = prices_fundamentals[prices_fundamentals['volume_quarter_avg'].notna()]

In [65]:
#use closest available volume average
prices_fundamentals["volume_semi_annual_avg"] = np.where(prices_fundamentals["volume_semi_annual_avg"].isnull(), prices_fundamentals["volume_quarter_avg"], prices_fundamentals["volume_semi_annual_avg"])
prices_fundamentals["volume_annual_avg"] = np.where(prices_fundamentals["volume_annual_avg"].isnull(), prices_fundamentals["volume_semi_annual_avg"], prices_fundamentals["volume_annual_avg"])
prices_fundamentals["volume_two_year_avg"] = np.where(prices_fundamentals["volume_two_year_avg"].isnull(), prices_fundamentals["volume_annual_avg"], prices_fundamentals["volume_two_year_avg"])
prices_fundamentals["volume_three_year_avg"] = np.where(prices_fundamentals["volume_three_year_avg"].isnull(), prices_fundamentals["volume_two_year_avg"], prices_fundamentals["volume_three_year_avg"])

In [66]:
prices_fundamentals["price_change_weekly_avg"] = prices_fundamentals.groupby("ticker")["price_change"].rolling(window=5).mean().reset_index(0,drop=True)
prices_fundamentals["price_change_month_avg"] = prices_fundamentals.groupby("ticker")["price_change"].rolling(window=21).mean().reset_index(0,drop=True)
prices_fundamentals["price_change_quarter_avg"] = prices_fundamentals.groupby("ticker")["price_change"].rolling(window=63).mean().reset_index(0,drop=True)
prices_fundamentals["price_change_semi_annual_avg"] = prices_fundamentals.groupby("ticker")["price_change"].rolling(window=126).mean().reset_index(0,drop=True)
prices_fundamentals["price_change_annual_avg"] = prices_fundamentals.groupby("ticker")["price_change"].rolling(window=253).mean().reset_index(0,drop=True)
prices_fundamentals["price_change_two_year_avg"] = prices_fundamentals.groupby("ticker")["price_change"].rolling(window=506).mean().reset_index(0,drop=True)
prices_fundamentals["price_change_three_year_avg"] = prices_fundamentals.groupby("ticker")["price_change"].rolling(window=759).mean().reset_index(0,drop=True)
prices_fundamentals

,ticker,date,close,volume,calendardate,accoci,assets,assetsavg,assetsc,assetsnc,...,volume_annual_avg,volume_two_year_avg,volume_three_year_avg,price_change_weekly_avg,price_change_month_avg,price_change_quarter_avg,price_change_semi_annual_avg,price_change_annual_avg,price_change_two_year_avg,price_change_three_year_avg
124,A,2017-09-29,64.20,1672816.0,2017-06-30,-417000000.0,8.261000e+09,7.987750e+09,3.996000e+09,4.265000e+09,...,1.648825e+06,1.648825e+06,1.648825e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,A,2017-10-02,64.87,1693854.0,2017-09-30,-346000000.0,8.426000e+09,8.143750e+09,4.169000e+09,4.257000e+09,...,1.652068e+06,1.652068e+06,1.652068e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,A,2017-10-03,65.15,1216981.0,2017-09-30,-346000000.0,8.426000e+09,8.143750e+09,4.169000e+09,4.257000e+09,...,1.645370e+06,1.645370e+06,1.645370e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,A,2017-10-04,65.83,745628.0,2017-09-30,-346000000.0,8.426000e+09,8.143750e+09,4.169000e+09,4.257000e+09,...,1.621498e+06,1.621498e+06,1.621498e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,A,2017-10-05,65.70,1974081.0,2017-09-30,-346000000.0,8.426000e+09,8.143750e+09,4.169000e+09,4.257000e+09,...,1.637508e+06,1.637508e+06,1.637508e+06,0.005331,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3112076,ZYXI,2021-02-23,18.07,646106.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,8.020958e+05,5.393672e+05,3.687291e+05,-0.006213,0.003009,0.005910,0.001978,0.003258,0.003726,0.003536
3112077,ZYXI,2021-02-24,18.42,315802.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,7.985637e+05,5.398170e+05,3.691079e+05,0.005666,0.000972,0.006146,0.002556,0.002834,0.003696,0.003540
3112078,ZYXI,2021-02-25,17.42,388872.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,7.982160e+05,5.404370e+05,3.695613e+05,0.002368,-0.002303,0.005048,0.001986,0.002809,0.003579,0.003494
3112079,ZYXI,2021-02-26,14.52,2337972.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,8.064176e+05,5.448817e+05,3.726145e+05,-0.037398,-0.017311,0.002615,0.000685,0.002179,0.003198,0.003275
3112080,ZYXI,2021-03-01,14.69,1244001.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,8.099665e+05,5.472455e+05,3.742248e+05,-0.047927,-0.013638,0.002824,0.001058,0.002448,0.003281,0.003273

In [67]:
#delete instances w/ < semi-annual year of history
prices_fundamentals = prices_fundamentals[prices_fundamentals['price_change_weekly_avg'].notna()]
prices_fundamentals = prices_fundamentals[prices_fundamentals['price_change_month_avg'].notna()]
prices_fundamentals = prices_fundamentals[prices_fundamentals['price_change_quarter_avg'].notna()]

In [68]:
#use closest available price_change average
prices_fundamentals["price_change_semi_annual_avg"] = np.where(prices_fundamentals["price_change_semi_annual_avg"].isnull(), prices_fundamentals["price_change_quarter_avg"], prices_fundamentals["price_change_semi_annual_avg"])
prices_fundamentals["price_change_annual_avg"] = np.where(prices_fundamentals["price_change_annual_avg"].isnull(), prices_fundamentals["price_change_semi_annual_avg"], prices_fundamentals["price_change_annual_avg"])
prices_fundamentals["price_change_two_year_avg"] = np.where(prices_fundamentals["price_change_two_year_avg"].isnull(), prices_fundamentals["price_change_annual_avg"], prices_fundamentals["price_change_two_year_avg"])
prices_fundamentals["price_change_three_year_avg"] = np.where(prices_fundamentals["price_change_three_year_avg"].isnull(), prices_fundamentals["price_change_two_year_avg"], prices_fundamentals["price_change_three_year_avg"])

In [69]:
prices_fundamentals["volume_change_weekly_avg"] = prices_fundamentals.groupby("ticker")["volume_change"].rolling(window=5).mean().reset_index(0,drop=True)
prices_fundamentals["volume_change_month_avg"] = prices_fundamentals.groupby("ticker")["volume_change"].rolling(window=21).mean().reset_index(0,drop=True)
prices_fundamentals["volume_change_quarter_avg"] = prices_fundamentals.groupby("ticker")["volume_change"].rolling(window=63).mean().reset_index(0,drop=True)
prices_fundamentals["volume_change_semi_annual_avg"] = prices_fundamentals.groupby("ticker")["volume_change"].rolling(window=126).mean().reset_index(0,drop=True)
prices_fundamentals["volume_change_annual_avg"] = prices_fundamentals.groupby("ticker")["volume_change"].rolling(window=253).mean().reset_index(0,drop=True)
prices_fundamentals["volume_change_two_year_avg"] = prices_fundamentals.groupby("ticker")["volume_change"].rolling(window=506).mean().reset_index(0,drop=True)
prices_fundamentals["volume_change_three_year_avg"] = prices_fundamentals.groupby("ticker")["volume_change"].rolling(window=759).mean().reset_index(0,drop=True)
prices_fundamentals

,ticker,date,close,volume,calendardate,accoci,assets,assetsavg,assetsc,assetsnc,...,price_change_annual_avg,price_change_two_year_avg,price_change_three_year_avg,volume_change_weekly_avg,volume_change_month_avg,volume_change_quarter_avg,volume_change_semi_annual_avg,volume_change_annual_avg,volume_change_two_year_avg,volume_change_three_year_avg
186,A,2017-12-28,67.45,607022.0,2017-09-30,-346000000.0,8.426000e+09,8.143750e+09,4.169000e+09,4.257000e+09,...,0.000883,0.000883,0.000883,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,A,2017-12-29,66.97,1064895.0,2017-09-30,-346000000.0,8.426000e+09,8.143750e+09,4.169000e+09,4.257000e+09,...,0.000715,0.000715,0.000715,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,A,2018-01-02,67.60,1047830.0,2017-12-31,-269000000.0,8.698000e+09,8.350250e+09,4.397000e+09,4.301000e+09,...,0.000699,0.000699,0.000699,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,A,2018-01-03,69.32,1698899.0,2017-12-31,-269000000.0,8.698000e+09,8.350250e+09,4.397000e+09,4.301000e+09,...,0.001034,0.001034,0.001034,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,A,2018-01-04,68.80,2231534.0,2017-12-31,-269000000.0,8.698000e+09,8.350250e+09,4.397000e+09,4.301000e+09,...,0.000750,0.000750,0.000750,0.251521,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3112076,ZYXI,2021-02-23,18.07,646106.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.003258,0.003726,0.003536,0.217214,0.115582,0.112060,0.179009,0.157662,0.228709,NaN
3112077,ZYXI,2021-02-24,18.42,315802.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.002834,0.003696,0.003540,0.055251,0.061852,0.101943,0.172574,0.152691,0.224603,NaN
3112078,ZYXI,2021-02-25,17.42,388872.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.002809,0.003579,0.003494,0.116534,0.079645,0.109426,0.171769,0.156000,0.225354,NaN
3112079,ZYXI,2021-02-26,14.52,2337972.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.002179,0.003198,0.003275,1.197035,0.239391,0.185196,0.215946,0.177583,0.234896,NaN
3112080,ZYXI,2021-03-01,14.69,1244001.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.002448,0.003281,0.003273,0.901636,0.238282,0.181890,0.204078,0.174484,0.234883,NaN

In [70]:
#delete instances w/ < semi-annual year of history
prices_fundamentals = prices_fundamentals[prices_fundamentals['volume_change_weekly_avg'].notna()]
prices_fundamentals = prices_fundamentals[prices_fundamentals['volume_change_month_avg'].notna()]
prices_fundamentals = prices_fundamentals[prices_fundamentals['volume_change_quarter_avg'].notna()]

In [71]:
#use closest available volume_change average
prices_fundamentals["volume_change_semi_annual_avg"] = np.where(prices_fundamentals["volume_change_semi_annual_avg"].isnull(), prices_fundamentals["volume_change_quarter_avg"], prices_fundamentals["volume_change_semi_annual_avg"])
prices_fundamentals["volume_change_annual_avg"] = np.where(prices_fundamentals["volume_change_annual_avg"].isnull(), prices_fundamentals["volume_change_semi_annual_avg"], prices_fundamentals["volume_change_annual_avg"])
prices_fundamentals["volume_change_two_year_avg"] = np.where(prices_fundamentals["volume_change_two_year_avg"].isnull(), prices_fundamentals["volume_change_annual_avg"], prices_fundamentals["volume_change_two_year_avg"])
prices_fundamentals["volume_change_three_year_avg"] = np.where(prices_fundamentals["volume_change_three_year_avg"].isnull(), prices_fundamentals["volume_change_two_year_avg"], prices_fundamentals["volume_change_three_year_avg"])

In [72]:
#replace inf values
prices_fundamentals.replace([np.inf, -np.inf], 0, inplace=True)

### Financial Ratios

In [73]:
#dividend yield
prices_fundamentals["divyield"] = prices_fundamentals["dps"] / prices_fundamentals["close"]

In [74]:
#market cap
prices_fundamentals["marketcap"] = prices_fundamentals["sharesbas"] * prices_fundamentals["close"] * prices_fundamentals["sharefactor"]

In [75]:
#enterprise value
prices_fundamentals["ev"] = prices_fundamentals["marketcap"] + prices_fundamentals["debt"] - prices_fundamentals["cashneq"]

In [76]:
#enterprise value over EBIT
prices_fundamentals["evebit"] = prices_fundamentals["ev"] / prices_fundamentals["ebit"]

In [77]:
#enterprise value over EBITDA
prices_fundamentals["evebit"] = prices_fundamentals["ev"] / prices_fundamentals["ebitda"]

In [78]:
#price to book
prices_fundamentals["pb"] = prices_fundamentals["marketcap"] / prices_fundamentals["equity"]

In [79]:
#price to earnings
prices_fundamentals["pe"] = prices_fundamentals["close"] / prices_fundamentals["eps"]

prices_fundamentals["pe"] = prices_fundamentals["pe"].replace([np.inf, -np.inf], 0)

In [80]:
#peg - 1
prices_fundamentals["peg1"] = prices_fundamentals["pe"] / prices_fundamentals["eps_1y_pct"]

prices_fundamentals["peg1"] = prices_fundamentals["peg1"].replace([np.inf, -np.inf], 0)

In [81]:
#peg - 2
prices_fundamentals["peg2"] = prices_fundamentals["pe"] / prices_fundamentals["eps_2y_pct"]

prices_fundamentals["peg2"] = prices_fundamentals["peg2"].replace([np.inf, -np.inf], 0)

In [82]:
#peg - 3
prices_fundamentals["peg3"] = prices_fundamentals["pe"] / prices_fundamentals["eps_3y_pct"]

prices_fundamentals["peg3"] = prices_fundamentals["peg3"].replace([np.inf, -np.inf], 0)

In [83]:
prices_fundamentals.to_pickle("prices_fundamentals.pkl")

### Merge Prices_Fundamentals and Ratings

In [80]:
quandl_df = pd.merge(prices_fundamentals, rh, how="left", on=["ticker", "date"])
quandl_df["rating_change"] = np.where(quandl_df.rating_mean_recom.isnull(), 0, 1)
quandl_df

,ticker,date,close,volume,calendardate,accoci,assets,assetsavg,assetsc,assetsnc,...,peg3,rating_cnt_strong_buys,rating_cnt_mod_buys,rating_cnt_holds,rating_cnt_mod_sells,rating_cnt_strong_sells,rating_mean_recom,rating_cnt_with,rating_cnt_without,rating_change
0,A,2018-03-29,66.90,2711285.0,2017-12-31,-269000000.0,8.698000e+09,8.350250e+09,4.397000e+09,4.301000e+09,...,-178.324278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,A,2018-04-02,64.43,3085753.0,2018-03-31,-310000000.0,8.784000e+09,8.542250e+09,4.525000e+09,4.259000e+09,...,-164.609213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,A,2018-04-03,65.42,2286132.0,2018-03-31,-310000000.0,8.784000e+09,8.542250e+09,4.525000e+09,4.259000e+09,...,-167.138518,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,A,2018-04-04,65.45,3702954.0,2018-03-31,-310000000.0,8.784000e+09,8.542250e+09,4.525000e+09,4.259000e+09,...,-167.215164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,A,2018-04-05,65.68,2118121.0,2018-03-31,-310000000.0,8.784000e+09,8.542250e+09,4.525000e+09,4.259000e+09,...,-167.802780,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2172405,ZYXI,2021-02-23,18.07,646106.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,384.824074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2172406,ZYXI,2021-02-24,18.42,315802.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,392.277778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2172407,ZYXI,2021-02-25,17.42,388872.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,370.981481,2.0,0.0,4.0,0.0,0.0,2.3,6.0,0.0,1
2172408,ZYXI,2021-02-26,14.52,2337972.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,309.222222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2172409,ZYXI,2021-03-01,14.69,1244001.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,312.842593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [81]:
quandl_df[['rating_cnt_strong_buys', 'rating_cnt_mod_buys', 'rating_cnt_holds', 'rating_cnt_mod_sells', 'rating_cnt_strong_sells', 'rating_mean_recom', 'rating_cnt_with', 'rating_cnt_without']] = quandl_df.groupby("ticker")\
    ['rating_cnt_strong_buys', 'rating_cnt_mod_buys', 'rating_cnt_holds', 'rating_cnt_mod_sells', 'rating_cnt_strong_sells', 'rating_mean_recom', 'rating_cnt_with', 'rating_cnt_without']\
    .transform(lambda x: x.fillna(method='ffill'))

<ipython-input-81-0904bc822241>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  quandl_df[['rating_cnt_strong_buys', 'rating_cnt_mod_buys', 'rating_cnt_holds', 'rating_cnt_mod_sells', 'rating_cnt_strong_sells', 'rating_mean_recom', 'rating_cnt_with', 'rating_cnt_without']] = quandl_df.groupby("ticker")\

In [82]:
quandl_df = quandl_df[quandl_df["rating_mean_recom"].notna()]

In [83]:
quandl_df.info(verbose=True, null_counts=True)

<ipython-input-83-53183cdb7b4a>:1: FutureWarning: null_counts is deprecated. Use show_counts instead
  quandl_df.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1334554 entries, 193 to 2172409
Data columns (total 180 columns):
 #    Column                         Non-Null Count    Dtype
---   ------                         --------------    -----
 0    ticker                         1334554 non-null  object
 1    date                           1334554 non-null  datetime64[ns]
 2    close                          1334554 non-null  float64
 3    volume                         1334554 non-null  float64
 4    calendardate                   1334554 non-null  object
 5    accoci                         1334554 non-null  float64
 6    assets                         1334554 non-null  float64
 7    assetsavg                      1334554 non-null  float64
 8    assetsc                        1334554 non-null  float64
 9    assetsnc                       1334554 non-null  float64
 10   assetturnover                  1334554 non-null  float64
 11   bvps                           1334554 non-null  float64
 12   capex                          1334554 non-null  float64
 13   cashneq                        1334554 non-null  float64
 14   cor                            1334554 non-null  float64
 15   consolinc                      1334554 non-null  float64
 16   currentratio                   1334554 non-null  float64
 17   de                             1334554 non-null  float64
 18   debt                           1334554 non-null  float64
 19   debtc                          1334554 non-null  float64
 20   debtnc                         1334554 non-null  float64
 21   deferredrev                    1334554 non-null  float64
 22   depamor                        1334554 non-null  float64
 23   deposits                       1334554 non-null  float64
 24   dps                            1334554 non-null  float64
 25   ebit                           1334554 non-null  float64
 26   ebitda                         1334554 non-null  float64
 27   ebitdamargin                   1334554 non-null  float64
 28   ebt                            1334554 non-null  float64
 29   eps                            1334554 non-null  float64
 30   epsdil                         1334554 non-null  float64
 31   equity                         1334554 non-null  float64
 32   equityavg                      1334554 non-null  float64
 33   fcf                            1334554 non-null  float64
 34   fcfps                          1334554 non-null  float64
 35   gp                             1334554 non-null  float64
 36   grossmargin                    1334554 non-null  float64
 37   intangibles                    1334554 non-null  float64
 38   intexp                         1334554 non-null  float64
 39   invcap                         1334554 non-null  float64
 40   invcapavg                      1334554 non-null  float64
 41   inventory                      1334554 non-null  float64
 42   investments                    1334554 non-null  float64
 43   investmentsc                   1334554 non-null  float64
 44   investmentsnc                  1334554 non-null  float64
 45   liabilities                    1334554 non-null  float64
 46   liabilitiesc                   1334554 non-null  float64
 47   liabilitiesnc                  1334554 non-null  float64
 48   ncf                            1334554 non-null  float64
 49   ncfbus                         1334554 non-null  float64
 50   ncfcommon                      1334554 non-null  float64
 51   ncfdebt                        1334554 non-null  float64
 52   ncfdiv                         1334554 non-null  float64
 53   ncff                           1334554 non-null  float64
 54   ncfi                           1334554 non-null  float64
 55   ncfinv                         1334554 non-null  float64
 56   ncfo                           1334554 non-null  float64
 57   ncfx                           1334554 non-null  float64
 58   netinc                         1334554 non-null  float64
 59   netinccmn                      1334554 non-null  float64
 60   netincdis                      1334554 non-null  float64
 61   netincnci                      1334554 non-null  float64
 62   netmargin                      1334554 non-null  float64
 63   opex                           1334554 non-null  float64
 64   opinc                          1334554 non-null  float64
 65   payables                       1334554 non-null  float64
 66   payoutratio                    1334554 non-null  float64
 67   ppnenet                        1334554 non-null  float64
 68   prefdivis                      1334554 non-null  float64
 69   ps                             1334554 non-null  float64
 70   ps1                            1334554 non-null  float64
 71   receivables                    1334554 non-null  float64
 72   retearn                        1334554 non-null  float64
 73   revenue                        1334554 non-null  float64
 74   rnd                            1334554 non-null  float64
 75   roa                            1334554 non-null  float64
 76   roe                            1334554 non-null  float64
 77   roic                           1334554 non-null  float64
 78   ros                            1334554 non-null  float64
 79   sbcomp                         1334554 non-null  float64
 80   sgna                           1334554 non-null  float64
 81   sharefactor                    1334554 non-null  float64
 82   sharesbas                      1334554 non-null  float64
 83   shareswa                       1334554 non-null  float64
 84   shareswadil                    1334554 non-null  float64
 85   sps                            1334554 non-null  float64
 86   tangibles                      1334554 non-null  float64
 87   taxassets                      1334554 non-null  float64
 88   taxexp                         1334554 non-null  float64
 89   taxliabilities                 1334554 non-null  float64
 90   tbvps                          1334554 non-null  float64
 91   workingcapital                 1334554 non-null  float64
 92   name                           1334554 non-null  object
 93   exchange                       1334554 non-null  object
 94   sector                         1334554 non-null  object
 95   industry                       1334554 non-null  object
 96   quart                          1334554 non-null  object
 97   year                           1334554 non-null  object
 98   revenue_1y_pct                 1334554 non-null  float64
 99   gp_1y_pct                      1334554 non-null  float64
 100  ebitda_1y_pct                  1334554 non-null  float64
 101  opinc_1y_pct                   1334554 non-null  float64
 102  netinc_1y_pct                  1334554 non-null  float64
 103  eps_1y_pct                     1334554 non-null  float64
 104  assets_1y_pct                  1334554 non-null  float64
 105  ncfo_1y_pct                    1334554 non-null  float64
 106  ncf_1y_pct                     1334554 non-null  float64
 107  equity_1y_pct                  1334554 non-null  float64
 108  revenue_2y_pct                 1334554 non-null  float64
 109  gp_2y_pct                      1334554 non-null  float64
 110  ebitda_2y_pct                  1334554 non-null  float64
 111  opinc_2y_pct                   1334554 non-null  float64
 112  netinc_2y_pct                  1334554 non-null  float64
 113  eps_2y_pct                     1334554 non-null  float64
 114  assets_2y_pct                  1334554 non-null  float64
 115  ncfo_2y_pct                    1334554 non-null  float64
 116  ncf_2y_pct                     1334554 non-null  float64
 117  equity_2y_pct                  1334554 non-null  float64
 118  revenue_3y_pct                 1334554 non-null  float64
 119  gp_3y_pct                      1334554 non-null  float64
 120  ebitda_3y_pct                  1334554 non-null  float64
 121  opinc_3y_pct                   1334554 non-null  float64
 122  netinc_3y_pct                  1334554 non-null  float64
 123  eps_3y_pct                     1334554 non-null  float64
 124  assets_3y_pct                  1334554 non-null  float64
 125  ncfo_3y_pct                    1334554 non-null  float64
 126  ncf_3y_pct                     1334554 non-null  float64
 127  equity_3y_pct                  1334554 non-null  float64
 128  volume_change                  1334554 non-null  float64
 129  price_change                   1334554 non-null  float64
 130  price_change_sector            1334554 non-null  float64
 131  price_change_norm_sector       1334554 non-null  float64
 132  price_change_industry          1334554 non-null  float64
 133  price_change_norm_industry     1334554 non-null  float64
 134  price_weekly_avg               1334554 non-null  float64
 135  price_month_avg                1334554 non-null  float64
 136  price_quarter_avg              1334554 non-null  float64
 137  price_semi_annual_avg          1334554 non-null  float64
 138  price_annual_avg               1334554 non-null  float64
 139  price_two_year_avg             1334554 non-null  float64
 140  price_three_year_avg           1334554 non-null  float64
 141  volume_weekly_avg              1334554 non-null  float64
 142  volume_month_avg               1334554 non-null  float64
 143  volume_quarter_avg             1334554 non-null  float64
 144  volume_semi_annual_avg         1334554 non-null  float64
 145  volume_annual_avg              1334554 non-null  float64
 146  volume_two_year_avg            1334554 non-null  float64
 147  volume_three_year_avg          1334554 non-null  float64
 148  price_change_weekly_avg        1334554 non-null  float64
 149  price_change_month_avg         1334554 non-null  float64
 150  price_change_quarter_avg       1334554 non-null  float64
 151  price_change_semi_annual_avg   1334554 non-null  float64
 152  price_change_annual_avg        1334554 non-null  float64
 153  price_change_two_year_avg      1334554 non-null  float64
 154  price_change_three_year_avg    1334554 non-null  float64
 155  volume_change_weekly_avg       1334554 non-null  float64
 156  volume_change_month_avg        1334554 non-null  float64
 157  volume_change_quarter_avg      1334554 non-null  float64
 158  volume_change_semi_annual_avg  1334554 non-null  float64
 159  volume_change_annual_avg       1334554 non-null  float64
 160  volume_change_two_year_avg     1334554 non-null  float64
 161  volume_change_three_year_avg   1334554 non-null  float64
 162  divyield                       1334554 non-null  float64
 163  marketcap                      1334554 non-null  float64
 164  ev                             1334554 non-null  float64
 165  evebit                         1334554 non-null  float64
 166  pb                             1334554 non-null  float64
 167  pe                             1334554 non-null  float64
 168  peg1                           1334554 non-null  float64
 169  peg2                           1334554 non-null  float64
 170  peg3                           1334554 non-null  float64
 171  rating_cnt_strong_buys         1334554 non-null  float64
 172  rating_cnt_mod_buys            1334554 non-null  float64
 173  rating_cnt_holds               1334554 non-null  float64
 174  rating_cnt_mod_sells           1334554 non-null  float64
 175  rating_cnt_strong_sells        1334554 non-null  float64
 176  rating_mean_recom              1334554 non-null  float64
 177  rating_cnt_with                1334554 non-null  float64
 178  rating_cnt_without             1334554 non-null  float64
 179  rating_change                  1334554 non-null  int64
dtypes: datetime64[ns](1), float64(170), int64(1), object(8)
memory usage: 1.8+ GB

In [84]:
quandl_df.reset_index(inplace=True, drop=True)
quandl_df

,ticker,date,close,volume,calendardate,accoci,assets,assetsavg,assetsc,assetsnc,...,peg3,rating_cnt_strong_buys,rating_cnt_mod_buys,rating_cnt_holds,rating_cnt_mod_sells,rating_cnt_strong_sells,rating_mean_recom,rating_cnt_with,rating_cnt_without,rating_change
0,A,2019-01-04,65.46,3123654.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,6.119574,8.0,2.0,0.0,0.0,0.0,1.1,10.0,0.0,1
1,A,2019-01-07,66.85,3235055.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,6.249519,8.0,2.0,0.0,0.0,0.0,1.1,10.0,0.0,0
2,A,2019-01-08,67.83,1578055.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,6.341135,8.0,2.0,0.0,0.0,0.0,1.1,10.0,0.0,0
3,A,2019-01-09,69.25,2442291.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,6.473885,8.0,2.0,0.0,0.0,0.0,1.1,10.0,0.0,0
4,A,2019-01-10,69.90,1080882.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,6.534650,8.0,2.0,0.0,0.0,0.0,1.1,10.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1334549,ZYXI,2021-02-23,18.07,646106.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,384.824074,3.0,0.0,3.0,0.0,0.0,2.0,6.0,0.0,0
1334550,ZYXI,2021-02-24,18.42,315802.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,392.277778,3.0,0.0,3.0,0.0,0.0,2.0,6.0,0.0,0
1334551,ZYXI,2021-02-25,17.42,388872.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,370.981481,2.0,0.0,4.0,0.0,0.0,2.3,6.0,0.0,1
1334552,ZYXI,2021-02-26,14.52,2337972.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,309.222222,2.0,0.0,4.0,0.0,0.0,2.3,6.0,0.0,0
1334553,ZYXI,2021-03-01,14.69,1244001.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,312.842593,2.0,0.0,4.0,0.0,0.0,2.3,6.0,0.0,0

In [85]:
quandl_df.to_pickle("quandl_df.pkl")

In [ ]:
core_tickers = list(quandl_df.ticker.unique())

In [ ]:
len(core_tickers)

### Export list of tickers for other API calls

In [149]:
core_tickers

['A',
 'AA',
 'AACH',
 'AAIC',
 'AAL',
 'AAOI',
 'AAON',
 'AAP',
 'AAPL',
 'AAT',
 'AAWW',
 'ABB',
 'ABBV',
 'ABC',
 'ABCB',
 'ABDC',
 'ABEO',
 'ABG',
 'ABM',
 'ABMD',
 'ABR',
 'ABT',
 'ABTX',
 'ABUS',
 'ACA',
 'ACAD',
 'ACBI',
 'ACC',
 'ACCO',
 'ACER',
 'ACETQ',
 'ACGL',
 'ACHC',
 'ACHN',
 'ACHV',
 'ACI',
 'ACIA',
 'ACIW',
 'ACLS',
 'ACM',
 'ACMR',
 'ACN',
 'ACOR',
 'ACRE',
 'ACRS',
 'ACRX',
 'ACTG',
 'ACU',
 'ACY',
 'ADAP',
 'ADBE',
 'ADC',
 'ADES',
 'ADI',
 'ADM',
 'ADMA',
 'ADMP',
 'ADMS',
 'ADNT',
 'ADOM',
 'ADP',
 'ADPT',
 'ADS',
 'ADSK',
 'ADSW',
 'ADT',
 'ADTN',
 'ADUS',
 'ADVM',
 'ADXS',
 'ADYX',
 'AEE',
 'AEGN',
 'AEIS',
 'AEL',
 'AEM',
 'AEMD',
 'AEO',
 'AEP',
 'AER',
 'AERI',
 'AES',
 'AESE',
 'AEYE',
 'AEZS',
 'AFG',
 'AFHIF',
 'AFI',
 'AFIN',
 'AFL',
 'AG',
 'AGCO',
 'AGEN',
 'AGFS',
 'AGHC',
 'AGI',
 'AGIO',
 'AGLE',
 'AGM',
 'AGN',
 'AGNC',
 'AGO',
 'AGR',
 'AGRO',
 'AGS',
 'AGTC',
 'AGX',
 'AGYS',
 'AHCO',
 'AHH',
 'AHL',
 'AHT',
 'AIG',
 'AIM',
 'AIMC',
 'AIN',
 'AINC',
 'AINV',
 'AIR',
 'AIRG',
 'AIRI',
 'AIT',
 'AIV',
 'AIZ',
 'AJG',
 'AJRD',
 'AJX',
 'AKAM',
 'AKAOQ',
 'AKBA',
 'AKCA',
 'AKR',
 'AKRXQ',
 'AKS',
 'AKTS',
 'AL',
 'ALB',
 'ALBO',
 'ALC',
 'ALCO',
 'ALE',
 'ALEC',
 'ALEX',
 'ALG',
 'ALGN',
 'ALGT',
 'ALIM',
 'ALK',
 'ALKS',
 'ALL',
 'ALLE',
 'ALLT',
 'ALLY',
 'ALNY',
 'ALO',
 'ALOT',
 'ALPN',
 'ALRM',
 'ALRS',
 'ALSK',
 'ALSN',
 'ALT',
 'ALTA',
 'ALTG',
 'ALTM',
 'ALTR',
 'ALV',
 'ALVR',
 'ALX',
 'ALXN',
 'AM',
 'AMAG',
 'AMAT',
 'AMBA',
 'AMBC',
 'AMBR',
 'AMC',
 'AMCR',
 'AMCX',
 'AMD',
 'AME',
 'AMED',
 'AMEH',
 'AMG',
 'AMGN',
 'AMH',
 'AMID',
 'AMK',
 'AMKR',
 'AMN',
 'AMNB',
 'AMOT',
 'AMP',
 'AMPE',
 'AMPH',
 'AMPY',
 'AMRB',
 'AMRC',
 'AMRK',
 'AMRN',
 'AMRQQ',
 'AMRS',
 'AMRX',
 'AMSC',
 'AMSF',
 'AMSWA',
 'AMT',
 'AMTB',
 'AMTD',
 'AMTX',
 'AMWD',
 'AMYT',
 'AMZN',
 'AN',
 'ANAB',
 'ANCX',
 'ANDE',
 'ANDX',
 'ANET',
 'ANF',
 'ANGI',
 'ANGO',
 'ANIK',
 'ANIP',
 'ANIX',
 'ANSS',
 'ANTM',
 'AON',
 'AOS',
 'AOSL',
 'APA',
 'APAM',
 'APC',
 'APD',
 'APDN',
 'APEI',
 'APEN',
 'APEX',
 'APH',
 'API',
 'APLE',
 'APO',
 'APOG',
 'APPF',
 'APPN',
 'APPS',
 'APRN',
 'APT',
 'APTI',
 'APTS',
 'APTV',
 'APTX',
 'APU',
 'APVO',
 'APYX',
 'AQ',
 'AQB',
 'AQMS',
 'AQN',
 'AQST',
 'AQUA',
 'AR',
 'ARA',
 'ARAV',
 'ARAY',
 'ARC',
 'ARCB',
 'ARCC',
 'ARCH',
 'ARCO',
 'ARCT',
 'ARDMQ',
 'ARDS',
 'ARDX',
 'ARE',
 'AREC',
 'ARES',
 'AREXQ',
 'ARGO',
 'ARI',
 'ARLO',
 'ARLP',
 'ARMK',
 'ARMP',
 'ARNA',
 'AROC',
 'AROW',
 'ARPO',
 'ARQL',
 'ARR',
 'ARRS',
 'ARTNA',
 'ARTX',
 'ARVN',
 'ARW',
 'ARWR',
 'ASB',
 'ASC',
 'ASCMA',
 'ASGN',
 'ASH',
 'ASIX',
 'ASLN',
 'ASMB',
 'ASNAQ',
 'ASPN',
 'ASPS',
 'ASPU',
 'ASRT',
 'AST',
 'ASTC',
 'ASTE',
 'ASUR',
 'ASV',
 'ASYS',
 'AT',
 'ATCO',
 'ATCX',
 'ATEC',
 'ATEN',
 'ATEX',
 'ATGE',
 'ATH',
 'ATHN',
 'ATHX',
 'ATI',
 'ATKR',
 'ATNI',
 'ATNX',
 'ATO',
 'ATOM',
 'ATOS',
 'ATR',
 'ATRC',
 'ATRI',
 'ATRO',
 'ATRS',
 'ATSG',
 'ATTO',
 'ATTU',
 'ATUS',
 'ATVI',
 'AU',
 'AUB',
 'AUDC',
 'AUMN',
 'AUPH',
 'AUTL',
 'AUTO',
 'AUY',
 'AVA',
 'AVAV',
 'AVB',
 'AVD',
 'AVDL',
 'AVEO',
 'AVGO',
 'AVGR',
 'AVID',
 'AVLR',
 'AVNS',
 'AVNT',
 'AVNW',
 'AVP',
 'AVT',
 'AVTR',
 'AVX',
 'AVY',
 'AVYA',
 'AWH',
 'AWI',
 'AWK',
 'AWR',
 'AX',
 'AXAS',
 'AXDX',
 'AXE',
 'AXGN',
 'AXL',
 'AXNX',
 'AXP',
 'AXS',
 'AXTA',
 'AXTI',
 'AY',
 'AYI',
 'AYR',
 'AYTU',
 'AYX',
 'AZEK',
 'AZN',
 'AZO',
 'AZPN',
 'AZZ',
 'B',
 'BA',
 'BAC',
 'BAH',
 'BALY',
 'BAM',
 'BANC',
 'BAND',
 'BANF',
 'BANR',
 'BASI',
 'BASX',
 'BAX',
 'BB',
 'BBBY',
 'BBCP',
 'BBDC',
 'BBGI',
 'BBI',
 'BBIO',
 'BBQ',
 'BBSI',
 'BBU',
 'BBW',
 'BBY',
 'BC',
 'BCBP',
 'BCC',
 'BCDA',
 'BCEI',
 'BCML',
 'BCO',
 'BCOR',
 'BCOV',
 'BCPC',
 'BCRHF',
 'BCRX',
 'BCSF',
 'BCYC',
 'BDC',
 'BDN',
 'BDSI',
 'BDX',
 'BE',
 'BEAT',
 'BECN',
 'BEEM',
 'BEL',
 'BELFA',
 'BEN',
 'BEP',
 'BERY',
 'BF.B',
 'BFAM',
 'BFC',
 'BFIN',
 'BFS',
 'BFST',
 'BFYT',
 'BG',
 'BGCP',
 'BGFV',
 'BGGSQ',
 'BGNE',
 'BGS',
 'BGSF',
 'BHBK',
 'BHC',
 'BHE',
 'BHF',
 'BHLB',
 'BHP',
 'BHR',
 'BHTG',
 'BID',
 'BIG',
 'BIIB',
 'BIO',
 'BIOC',
 'BIOL',
 'BIOX',
 'BIP',
 'BJ',
 'BJRI',
 'BK',
 'BKCC',
 'BKD',
 'BKE',
 'BKEP',
 'BKH',
 'BKI',
 'BKMU',
 'BKNG',
 'BKR',
 'BKS',
 'BKU',
 'BKYI',
 'BL',
 'BLBD',
 'BLCM',
 'BLD',
 'BLDP',
 'BLDR',
 'BLFS',
 'BLIN',
 'BLK',
 'BLKB',
 'BLL',
 'BLMN',
 'BLNK',
 'BLUE',
 'BLX',
 'BMCH',
 'BMI',
 'BMRA',
 'BMRC',
 'BMRN',
 'BMTC',
 'BMTM',
 'BMY',
 'BNCL',
 'BNED',
 'BNFT',
 'BNGO',
 'BNL',
 'BNTC',
 'BOCH',
 'BOH',
 'BOJA',
 'BOKF',
 'BOMN',
 'BOOM',
 'BOOT',
 'BORR',
 'BOX',
 'BOXL',
 'BP',
 'BPFH',
 'BPL',
 'BPMC',
 'BPMP',
 'BPOP',
 'BPTH',
 'BPY',
 'BR',
 'BRC',
 'BREW',
 'BRG',
 'BRK.B',
 'BRKL',
 'BRKR',
 'BRKS',
 'BRMK',
 'BRO',
 'BRSS',
 'BRSWQ',
 'BRT',
 'BRX',
 'BRY',
 'BSET',
 'BSIG',
 'BSM',
 'BSRR',
 'BSTC',
 'BSVN',
 'BSX',
 'BSY',
 'BTG',
 'BTU',
 'BUD',
 'BURL',
 'BUSE',
 'BV',
 'BVH',
 'BVN',
 'BW',
 'BWA',
 'BWAY',
 'BWB',
 'BWEN',
 'BWFG',
 'BWLD',
 'BWXT',
 'BX',
 'BXC',
 'BXG',
 'BXMT',
 'BXP',
 'BXS',
 'BY',
 'BYD',
 'BYND',
 'BZH',
 'C',
 'CAAP',
 'CAAS',
 'CABO',
 'CAC',
 'CACC',
 'CACI',
 'CADE',
 'CAG',
 'CAH',
 'CAI',
 'CAKE',
 'CAL',
 'CALA',
 'CALM',
 'CALX',
 'CAMP',
 'CAMT',
 'CAPL',
 'CAPR',
 'CAR',
 'CARA',
 'CARB',
 'CARG',
 'CARO',
 'CARS',
 'CASA',
 'CASH',
 'CASI',
 'CASY',
 'CAT',
 'CATB',
 'CATC',
 'CATM',
 'CATY',
 'CB',
 'CBAY',
 'CBB',
 'CBFV',
 'CBIO',
 'CBKCQ',
 'CBLK',
 'CBM',
 'CBMG',
 'CBNK',
 'CBOE',
 'CBPO',
 'CBPX',
 'CBRE',
 'CBRL',
 'CBSH',
 'CBT',
 'CBTX',
 'CBU',
 'CBZ',
 'CC',
 'CCAP',
 'CCB',
 'CCBG',
 'CCI',
 'CCK',
 'CCL',
 'CCLP',
 'CCMP',
 'CCNE',
 'CCO',
 'CCOI',
 'CCR',
 'CCRN',
 'CCS',
 'CCXI',
 'CDAY',
 'CDE',
 'CDEV',
 'CDK',
 'CDLX',
 'CDMO',
 'CDNA',
 'CDNS',
 'CDOR',
 'CDR',
 'CDTX',
 'CDW',
 'CDXC',
 'CDXS',
 'CDZI',
 'CE',
 'CECE',
 'CEIX',
 'CELG',
 'CELH',
 'CELP',
 'CEMI',
 'CENT',
 'CENX',
 'CEQP',
 'CERC',
 'CERN',
 'CERS',
 'CETX',
 'CEVA',
 'CF',
 'CFB',
 'CFBK',
 'CFFN',
 'CFG',
 'CFMS',
 'CFR',
 'CFX',
 'CG',
 'CGBD',
 'CGEN',
 'CGIX',
 'CGNX',
 'CHCO',
 'CHCT',
 'CHD',
 'CHDN',
 'CHE',
 'CHEF',
 'CHFS',
 'CHGG',
 'CHH',
 'CHKAQ',
 'CHKP',
 'CHMG',
 'CHMI',
 'CHRA',
 'CHRS',
 'CHRW',
 'CHS',
 'CHSP',
 'CHTR',
 'CHUY',
 'CHWY',
 'CHX',
 'CI',
 'CIDM',
 'CIEN',
 'CIGI',
 'CIM',
 'CINF',
 'CINR',
 'CIO',
 'CIR',
 'CISN',
 'CIT',
 'CIVB',
 'CIVI',
 'CJ',
 'CKH',
 'CKPT',
 'CL',
 'CLAR',
 'CLB',
 'CLBK',
 'CLBS',
 'CLDPQ',
 'CLDR',
 'CLDT',
 'CLDX',
 'CLF',
 'CLFD',
 'CLGN',
 'CLGX',
 'CLH',
 'CLI',
 'CLIR',
 'CLMT',
 'CLNC',
 'CLNE',
 'CLNN',
 'CLNY',
 'CLPR',
 'CLPT',
 'CLR',
 'CLRO',
 'CLS',
 'CLSD',
 'CLSK',
 'CLSN',
 'CLUBQ',
 'CLVS',
 'CLW',
 'CLX',
 'CLXT',
 'CMA',
 'CMBM',
 'CMC',
 'CMCO',
 'CMCSA',
 'CMD',
 'CME',
 'CMG',
 'CMI',
 'CMLS',
 'CMO',
 'CMP',
 'CMPR',
 'CMRE',
 'CMRX',
 'CMS',
 'CMTL',
 'CNA',
 'CNC',
 'CNCE',
 'CNDT',
 'CNFR',
 'CNHI',
 'CNK',
 'CNMD',
 'CNNE',
 'CNO',
 'CNOB',
 'CNP',
 'CNR',
 'CNS',
 'CNSL',
 'CNTY',
 'CNX',
 'CNXM',
 'CNXN',
 'COCP',
 'CODI',
 'CODX',
 'COF',
 'COG',
 'COGT',
 'COHR',
 'COHU',
 'COLB',
 'COLD',
 'COLL',
 'COLM',
 'COMM',
 'CONE',
 'CONN',
 'COO',
 'COOP',
 'COP',
 'COR',
 'CORE',
 'CORR',
 'CORT',
 'CORV',
 'COST',
 'COTY',
 'COUP',
 'COWN',
 'CPA',
 'CPB',
 'CPE',
 'CPF',
 'CPIX',
 'CPK',
 'CPLG',
 'CPLP',
 'CPPRQ',
 'CPRI',
 'CPRT',
 'CPRX',
 'CPS',
 'CPSI',
 'CPSS',
 'CPST',
 'CPT',
 'CPTA',
 'CQP',
 'CR',
 'CRAI',
 'CRAY',
 'CRBP',
 'CRCM',
 'CRCQQ',
 'CRDF',
 'CREE',
 'CREX',
 'CRHM',
 'CRI',
 'CRIS',
 'CRK',
 'CRL',
 'CRM',
 'CRMD',
 'CRMT',
 'CRNT',
 'CRNX',
 'CRON',
 'CROX',
 'CRRTQ',
 'CRS',
 'CRSP',
 'CRTO',
 'CRUS',
 'CRWD',
 'CRWS',
 'CRY',
 'CRZO',
 'CSBR',
 'CSCO',
 'CSFL',
 'CSGP',
 'CSGS',
 'CSII',
 'CSIQ',
 'CSL',
 'CSLT',
 'CSOD',
 'CSPR',
 'CSR',
 'CSS',
 'CSSE',
 'CSTE',
 'CSTL',
 'CSTR',
 'CSU',
 'CSV',
 'CSWC',
 'CSWI',
 'CSX',
 'CTAS',
 'CTB',
 'CTBI',
 'CTEK',
 'CTG',
 'CTHR',
 'CTIC',
 'CTK',
 'CTLT',
 'CTMX',
 'CTO',
 'CTRCQ',
 'CTRE',
 'CTRL',
 'CTRN',
 'CTS',
 'CTSH',
 'CTSO',
 'CTST',
 'CTT',
 'CTVA',
 'CTWS',
 'CTXS',
 'CUB',
 'CUBE',
 'CUBI',
 'CUE',
 'CULP',
 'CURO',
 'CUTR',
 'CUZ',
 'CVA',
 'CVBF',
 'CVCO',
 'CVCY',
 'CVEO',
 'CVET',
 'CVGI',
 'CVGW',
 'CVI',
 'CVLG',
 'CVLT',
 'CVM',
 'CVNA',
 'CVRR',
 'CVRS',
 'CVS',
 'CVU',
 'CVX',
 'CW',
 'CWCO',
 'CWEN',
 'CWH',
 'CWK',
 'CWST',
 'CWT',
 'CX',
 'CXDO',
 'CXO',
 'CXP',
 'CXW',
 'CY',
 'CYBE',
 'CYBR',
 'CYCC',
 'CYH',
 'CYOU',
 'CYRN',
 'CYRX',
 'CYTH',
 'CYTK',
 'CYTR',
 'CZFS',
 'CZNC',
 'CZR',
 'CZWI',
 'D',
 'DAC',
 'DAKT',
 'DAL',
 'DAN',
 'DAR',
 'DARE',
 'DATA',
 'DBD',
 'DBI',
 'DBX',
 'DCI',
 'DCO',
 'DCOM',
 'DCP',
 'DCPH',
 'DCTH',
 ...]

In [150]:
import pickle
outfile = open("core_tickers.pkl", 'wb')
pickle.dump(core_tickers, outfile)
outfile.close()