In [20]:
import pandas as pd
import numpy as np
import pickle

### Import Quandl DataFrame

In [2]:
quandl_df = pd.read_pickle("quandl_df.pkl")
quandl_df

,ticker,date,close,volume,calendardate,accoci,assets,assetsavg,assetsc,assetsnc,...,peg3,rating_cnt_strong_buys,rating_cnt_mod_buys,rating_cnt_holds,rating_cnt_mod_sells,rating_cnt_strong_sells,rating_mean_recom,rating_cnt_with,rating_cnt_without,rating_change
0,A,2019-01-04,65.46,3123654.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,6.119574,8.0,2.0,0.0,0.0,0.0,1.1,10.0,0.0,1
1,A,2019-01-07,66.85,3235055.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,6.249519,8.0,2.0,0.0,0.0,0.0,1.1,10.0,0.0,0
2,A,2019-01-08,67.83,1578055.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,6.341135,8.0,2.0,0.0,0.0,0.0,1.1,10.0,0.0,0
3,A,2019-01-09,69.25,2442291.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,6.473885,8.0,2.0,0.0,0.0,0.0,1.1,10.0,0.0,0
4,A,2019-01-10,69.90,1080882.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,6.534650,8.0,2.0,0.0,0.0,0.0,1.1,10.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1334549,ZYXI,2021-02-23,18.07,646106.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,384.824074,3.0,0.0,3.0,0.0,0.0,2.0,6.0,0.0,0
1334550,ZYXI,2021-02-24,18.42,315802.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,392.277778,3.0,0.0,3.0,0.0,0.0,2.0,6.0,0.0,0
1334551,ZYXI,2021-02-25,17.42,388872.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,370.981481,2.0,0.0,4.0,0.0,0.0,2.3,6.0,0.0,1
1334552,ZYXI,2021-02-26,14.52,2337972.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,309.222222,2.0,0.0,4.0,0.0,0.0,2.3,6.0,0.0,0
1334553,ZYXI,2021-03-01,14.69,1244001.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,312.842593,2.0,0.0,4.0,0.0,0.0,2.3,6.0,0.0,0

### Import DCF Dataframe

In [3]:
dcf = pd.read_pickle("dcf.pkl")
dcf.rename(columns={"symbol":"ticker"}, inplace=True)
dcf

        ticker        date         dcf
0            A  2021-03-10  124.263310
1            A  2021-03-09  124.113312
2            A  2021-03-08  120.353312
3            A  2021-03-05  120.413311
4            A  2021-03-04  119.263312
...        ...         ...         ...
2227289   ZYXI  2020-07-28   19.002761
2227290   ZYXI  2020-07-27   19.936412
2227291   ZYXI  2020-07-24   20.136411
2227292   ZYXI  2020-07-23   20.636411
2227293   ZYXI  2020-07-22   21.986411

[2227294 rows x 3 columns]

In [4]:
dcf["date"] = pd.to_datetime(dcf["date"])

In [5]:
quandl_dcf = pd.merge(quandl_df, dcf, on=["ticker", "date"], how='inner')
quandl_dcf

,ticker,date,close,volume,calendardate,accoci,assets,assetsavg,assetsc,assetsnc,...,rating_cnt_strong_buys,rating_cnt_mod_buys,rating_cnt_holds,rating_cnt_mod_sells,rating_cnt_strong_sells,rating_mean_recom,rating_cnt_with,rating_cnt_without,rating_change,dcf
0,A,2019-01-04,65.46,3123654.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,8.0,2.0,0.0,0.0,0.0,1.1,10.0,0.0,1,72.373846
1,A,2019-01-07,66.85,3235055.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,8.0,2.0,0.0,0.0,0.0,1.1,10.0,0.0,0,73.763846
2,A,2019-01-08,67.83,1578055.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,8.0,2.0,0.0,0.0,0.0,1.1,10.0,0.0,0,74.743846
3,A,2019-01-09,69.25,2442291.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,8.0,2.0,0.0,0.0,0.0,1.1,10.0,0.0,0,76.163846
4,A,2019-01-10,69.90,1080882.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,8.0,2.0,0.0,0.0,0.0,1.1,10.0,0.0,0,76.813846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1190899,ZYXI,2021-02-23,18.07,646106.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,3.0,0.0,3.0,0.0,0.0,2.0,6.0,0.0,0,19.232166
1190900,ZYXI,2021-02-24,18.42,315802.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,3.0,0.0,3.0,0.0,0.0,2.0,6.0,0.0,0,19.582166
1190901,ZYXI,2021-02-25,17.42,388872.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,2.0,0.0,4.0,0.0,0.0,2.3,6.0,0.0,1,18.524211
1190902,ZYXI,2021-02-26,14.52,2337972.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,2.0,0.0,4.0,0.0,0.0,2.3,6.0,0.0,0,15.624211
1190903,ZYXI,2021-03-01,14.69,1244001.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,2.0,0.0,4.0,0.0,0.0,2.3,6.0,0.0,0,15.794211

### Import Earnings Surprises DataFrame

In [6]:
surprise = pd.read_pickle("surprise.pkl")

In [7]:
surprise["date"] = pd.to_datetime(surprise["date"])

In [8]:
surprise["earnings_surprise"] = surprise["actualEarningResult"] - surprise["estimatedEarning"]

In [9]:
surprise.rename(columns={"symbol":"ticker"}, inplace=True)

In [10]:
surprise

,date,ticker,actualEarningResult,estimatedEarning,earnings_surprise
0,2021-02-16,A,1.06,0.89,0.17
1,2020-11-23,A,0.98,0.93,0.05
2,2020-08-18,A,0.78,0.66,0.12
3,2020-05-21,A,0.71,0.61,0.10
4,2020-02-18,A,0.81,0.81,0.00
...,...,...,...,...,...
36683,2019-10-29,ZYXI,0.06,0.06,0.00
36684,2019-07-31,ZYXI,0.06,0.06,0.00
36685,2019-04-30,ZYXI,0.07,0.05,0.02
36686,2019-02-26,ZYXI,0.08,0.07,0.01
36687,2018-11-06,ZYXI,0.08,0.06,0.02

In [11]:
quandl_dcf_surprise = pd.merge(quandl_dcf, surprise, on=["date", "ticker"], how="left")
quandl_dcf_surprise

,ticker,date,close,volume,calendardate,accoci,assets,assetsavg,assetsc,assetsnc,...,rating_cnt_mod_sells,rating_cnt_strong_sells,rating_mean_recom,rating_cnt_with,rating_cnt_without,rating_change,dcf,actualEarningResult,estimatedEarning,earnings_surprise
0,A,2019-01-04,65.46,3123654.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,0.0,0.0,1.1,10.0,0.0,1,72.373846,NaN,NaN,NaN
1,A,2019-01-07,66.85,3235055.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,0.0,0.0,1.1,10.0,0.0,0,73.763846,NaN,NaN,NaN
2,A,2019-01-08,67.83,1578055.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,0.0,0.0,1.1,10.0,0.0,0,74.743846,NaN,NaN,NaN
3,A,2019-01-09,69.25,2442291.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,0.0,0.0,1.1,10.0,0.0,0,76.163846,NaN,NaN,NaN
4,A,2019-01-10,69.90,1080882.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,0.0,0.0,1.1,10.0,0.0,0,76.813846,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1190899,ZYXI,2021-02-23,18.07,646106.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.0,0.0,2.0,6.0,0.0,0,19.232166,NaN,NaN,NaN
1190900,ZYXI,2021-02-24,18.42,315802.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.0,0.0,2.0,6.0,0.0,0,19.582166,NaN,NaN,NaN
1190901,ZYXI,2021-02-25,17.42,388872.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.0,0.0,2.3,6.0,0.0,1,18.524211,0.05,0.06,-0.01
1190902,ZYXI,2021-02-26,14.52,2337972.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.0,0.0,2.3,6.0,0.0,0,15.624211,NaN,NaN,NaN
1190903,ZYXI,2021-03-01,14.69,1244001.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.0,0.0,2.3,6.0,0.0,0,15.794211,NaN,NaN,NaN

In [12]:
quandl_dcf_surprise[['actualEarningResult', 'estimatedEarning', 'earnings_surprise']] = quandl_dcf_surprise.groupby("ticker")\
    ['actualEarningResult', 'estimatedEarning', 'earnings_surprise']\
    .transform(lambda x: x.fillna(method='ffill'))

<ipython-input-12-cb345e663540>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  quandl_dcf_surprise[['actualEarningResult', 'estimatedEarning', 'earnings_surprise']] = quandl_dcf_surprise.groupby("ticker")\

In [13]:
quandl_dcf_surprise = quandl_dcf_surprise[quandl_dcf_surprise["earnings_surprise"].notna()]

In [14]:
quandl_dcf_surprise

,ticker,date,close,volume,calendardate,accoci,assets,assetsavg,assetsc,assetsnc,...,rating_cnt_mod_sells,rating_cnt_strong_sells,rating_mean_recom,rating_cnt_with,rating_cnt_without,rating_change,dcf,actualEarningResult,estimatedEarning,earnings_surprise
31,A,2019-02-20,78.56,2076523.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,0.0,0.0,1.1,10.0,0.0,0,84.948199,0.76,0.73,0.03
32,A,2019-02-21,77.89,3570828.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,0.0,0.0,1.1,10.0,0.0,0,84.278199,0.76,0.73,0.03
33,A,2019-02-22,78.42,2797669.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,0.0,0.0,1.1,10.0,0.0,1,84.808199,0.76,0.73,0.03
34,A,2019-02-25,79.34,1878041.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,0.0,0.0,1.1,10.0,0.0,0,85.728199,0.76,0.73,0.03
35,A,2019-02-26,78.55,1992595.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,0.0,0.0,1.1,10.0,0.0,0,84.938199,0.76,0.73,0.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1190899,ZYXI,2021-02-23,18.07,646106.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.0,0.0,2.0,6.0,0.0,0,19.232166,0.04,0.05,-0.01
1190900,ZYXI,2021-02-24,18.42,315802.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.0,0.0,2.0,6.0,0.0,0,19.582166,0.04,0.05,-0.01
1190901,ZYXI,2021-02-25,17.42,388872.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.0,0.0,2.3,6.0,0.0,1,18.524211,0.05,0.06,-0.01
1190902,ZYXI,2021-02-26,14.52,2337972.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.0,0.0,2.3,6.0,0.0,0,15.624211,0.05,0.06,-0.01
1190903,ZYXI,2021-03-01,14.69,1244001.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.0,0.0,2.3,6.0,0.0,0,15.794211,0.05,0.06,-0.01

In [15]:
quandl_dcf_surprise.reset_index(inplace=True, drop=True)
quandl_dcf_surprise

,ticker,date,close,volume,calendardate,accoci,assets,assetsavg,assetsc,assetsnc,...,rating_cnt_mod_sells,rating_cnt_strong_sells,rating_mean_recom,rating_cnt_with,rating_cnt_without,rating_change,dcf,actualEarningResult,estimatedEarning,earnings_surprise
0,A,2019-02-20,78.56,2076523.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,0.0,0.0,1.1,10.0,0.0,0,84.948199,0.76,0.73,0.03
1,A,2019-02-21,77.89,3570828.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,0.0,0.0,1.1,10.0,0.0,0,84.278199,0.76,0.73,0.03
2,A,2019-02-22,78.42,2797669.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,0.0,0.0,1.1,10.0,0.0,1,84.808199,0.76,0.73,0.03
3,A,2019-02-25,79.34,1878041.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,0.0,0.0,1.1,10.0,0.0,0,85.728199,0.76,0.73,0.03
4,A,2019-02-26,78.55,1992595.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,0.0,0.0,1.1,10.0,0.0,0,84.938199,0.76,0.73,0.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1081588,ZYXI,2021-02-23,18.07,646106.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.0,0.0,2.0,6.0,0.0,0,19.232166,0.04,0.05,-0.01
1081589,ZYXI,2021-02-24,18.42,315802.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.0,0.0,2.0,6.0,0.0,0,19.582166,0.04,0.05,-0.01
1081590,ZYXI,2021-02-25,17.42,388872.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.0,0.0,2.3,6.0,0.0,1,18.524211,0.05,0.06,-0.01
1081591,ZYXI,2021-02-26,14.52,2337972.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.0,0.0,2.3,6.0,0.0,0,15.624211,0.05,0.06,-0.01
1081592,ZYXI,2021-03-01,14.69,1244001.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.0,0.0,2.3,6.0,0.0,0,15.794211,0.05,0.06,-0.01

### Investigate and Export Final Dataframe

In [16]:
final_df = quandl_dcf_surprise

In [17]:
final_df

,ticker,date,close,volume,calendardate,accoci,assets,assetsavg,assetsc,assetsnc,...,rating_cnt_mod_sells,rating_cnt_strong_sells,rating_mean_recom,rating_cnt_with,rating_cnt_without,rating_change,dcf,actualEarningResult,estimatedEarning,earnings_surprise
0,A,2019-02-20,78.56,2076523.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,0.0,0.0,1.1,10.0,0.0,0,84.948199,0.76,0.73,0.03
1,A,2019-02-21,77.89,3570828.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,0.0,0.0,1.1,10.0,0.0,0,84.278199,0.76,0.73,0.03
2,A,2019-02-22,78.42,2797669.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,0.0,0.0,1.1,10.0,0.0,1,84.808199,0.76,0.73,0.03
3,A,2019-02-25,79.34,1878041.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,0.0,0.0,1.1,10.0,0.0,0,85.728199,0.76,0.73,0.03
4,A,2019-02-26,78.55,1992595.0,2018-12-31,-381000000.0,8.952000e+09,8.656500e+09,3.712000e+09,5.240000e+09,...,0.0,0.0,1.1,10.0,0.0,0,84.938199,0.76,0.73,0.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1081588,ZYXI,2021-02-23,18.07,646106.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.0,0.0,2.0,6.0,0.0,0,19.232166,0.04,0.05,-0.01
1081589,ZYXI,2021-02-24,18.42,315802.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.0,0.0,2.0,6.0,0.0,0,19.582166,0.04,0.05,-0.01
1081590,ZYXI,2021-02-25,17.42,388872.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.0,0.0,2.3,6.0,0.0,1,18.524211,0.05,0.06,-0.01
1081591,ZYXI,2021-02-26,14.52,2337972.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.0,0.0,2.3,6.0,0.0,0,15.624211,0.05,0.06,-0.01
1081592,ZYXI,2021-03-01,14.69,1244001.0,2020-12-31,0.0,7.217500e+07,5.178025e+07,6.302300e+07,9.152000e+06,...,0.0,0.0,2.3,6.0,0.0,0,15.794211,0.05,0.06,-0.01

In [56]:
final_df.info(verbose=True, null_counts=True)

<ipython-input-56-87d063124f56>:1: FutureWarning: null_counts is deprecated. Use show_counts instead
  final_df.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1081593 entries, 0 to 1081592
Data columns (total 184 columns):
 #    Column                         Non-Null Count    Dtype
---   ------                         --------------    -----
 0    ticker                         1081593 non-null  object
 1    date                           1081593 non-null  datetime64[ns]
 2    close                          1081593 non-null  float64
 3    volume                         1081593 non-null  float64
 4    calendardate                   1081593 non-null  object
 5    accoci                         1081593 non-null  float64
 6    assets                         1081593 non-null  float64
 7    assetsavg                      1081593 non-null  float64
 8    assetsc                        1081593 non-null  float64
 9    assetsnc                       1081593 non-null  float64
 10   assetturnover                  1081593 non-null  float64
 11   bvps                           1081593 non-null  float64
 12   capex                          1081593 non-null  float64
 13   cashneq                        1081593 non-null  float64
 14   cor                            1081593 non-null  float64
 15   consolinc                      1081593 non-null  float64
 16   currentratio                   1081593 non-null  float64
 17   de                             1081593 non-null  float64
 18   debt                           1081593 non-null  float64
 19   debtc                          1081593 non-null  float64
 20   debtnc                         1081593 non-null  float64
 21   deferredrev                    1081593 non-null  float64
 22   depamor                        1081593 non-null  float64
 23   deposits                       1081593 non-null  float64
 24   dps                            1081593 non-null  float64
 25   ebit                           1081593 non-null  float64
 26   ebitda                         1081593 non-null  float64
 27   ebitdamargin                   1081593 non-null  float64
 28   ebt                            1081593 non-null  float64
 29   eps                            1081593 non-null  float64
 30   epsdil                         1081593 non-null  float64
 31   equity                         1081593 non-null  float64
 32   equityavg                      1081593 non-null  float64
 33   fcf                            1081593 non-null  float64
 34   fcfps                          1081593 non-null  float64
 35   gp                             1081593 non-null  float64
 36   grossmargin                    1081593 non-null  float64
 37   intangibles                    1081593 non-null  float64
 38   intexp                         1081593 non-null  float64
 39   invcap                         1081593 non-null  float64
 40   invcapavg                      1081593 non-null  float64
 41   inventory                      1081593 non-null  float64
 42   investments                    1081593 non-null  float64
 43   investmentsc                   1081593 non-null  float64
 44   investmentsnc                  1081593 non-null  float64
 45   liabilities                    1081593 non-null  float64
 46   liabilitiesc                   1081593 non-null  float64
 47   liabilitiesnc                  1081593 non-null  float64
 48   ncf                            1081593 non-null  float64
 49   ncfbus                         1081593 non-null  float64
 50   ncfcommon                      1081593 non-null  float64
 51   ncfdebt                        1081593 non-null  float64
 52   ncfdiv                         1081593 non-null  float64
 53   ncff                           1081593 non-null  float64
 54   ncfi                           1081593 non-null  float64
 55   ncfinv                         1081593 non-null  float64
 56   ncfo                           1081593 non-null  float64
 57   ncfx                           1081593 non-null  float64
 58   netinc                         1081593 non-null  float64
 59   netinccmn                      1081593 non-null  float64
 60   netincdis                      1081593 non-null  float64
 61   netincnci                      1081593 non-null  float64
 62   netmargin                      1081593 non-null  float64
 63   opex                           1081593 non-null  float64
 64   opinc                          1081593 non-null  float64
 65   payables                       1081593 non-null  float64
 66   payoutratio                    1081593 non-null  float64
 67   ppnenet                        1081593 non-null  float64
 68   prefdivis                      1081593 non-null  float64
 69   ps                             1081593 non-null  float64
 70   ps1                            1081593 non-null  float64
 71   receivables                    1081593 non-null  float64
 72   retearn                        1081593 non-null  float64
 73   revenue                        1081593 non-null  float64
 74   rnd                            1081593 non-null  float64
 75   roa                            1081593 non-null  float64
 76   roe                            1081593 non-null  float64
 77   roic                           1081593 non-null  float64
 78   ros                            1081593 non-null  float64
 79   sbcomp                         1081593 non-null  float64
 80   sgna                           1081593 non-null  float64
 81   sharefactor                    1081593 non-null  float64
 82   sharesbas                      1081593 non-null  float64
 83   shareswa                       1081593 non-null  float64
 84   shareswadil                    1081593 non-null  float64
 85   sps                            1081593 non-null  float64
 86   tangibles                      1081593 non-null  float64
 87   taxassets                      1081593 non-null  float64
 88   taxexp                         1081593 non-null  float64
 89   taxliabilities                 1081593 non-null  float64
 90   tbvps                          1081593 non-null  float64
 91   workingcapital                 1081593 non-null  float64
 92   name                           1081593 non-null  object
 93   exchange                       1081593 non-null  object
 94   sector                         1081593 non-null  object
 95   industry                       1081593 non-null  object
 96   quart                          1081593 non-null  object
 97   year                           1081593 non-null  object
 98   revenue_1y_pct                 1081593 non-null  float64
 99   gp_1y_pct                      1081593 non-null  float64
 100  ebitda_1y_pct                  1081593 non-null  float64
 101  opinc_1y_pct                   1081593 non-null  float64
 102  netinc_1y_pct                  1081593 non-null  float64
 103  eps_1y_pct                     1081593 non-null  float64
 104  assets_1y_pct                  1081593 non-null  float64
 105  ncfo_1y_pct                    1081593 non-null  float64
 106  ncf_1y_pct                     1081593 non-null  float64
 107  equity_1y_pct                  1081593 non-null  float64
 108  revenue_2y_pct                 1081593 non-null  float64
 109  gp_2y_pct                      1081593 non-null  float64
 110  ebitda_2y_pct                  1081593 non-null  float64
 111  opinc_2y_pct                   1081593 non-null  float64
 112  netinc_2y_pct                  1081593 non-null  float64
 113  eps_2y_pct                     1081593 non-null  float64
 114  assets_2y_pct                  1081593 non-null  float64
 115  ncfo_2y_pct                    1081593 non-null  float64
 116  ncf_2y_pct                     1081593 non-null  float64
 117  equity_2y_pct                  1081593 non-null  float64
 118  revenue_3y_pct                 1081593 non-null  float64
 119  gp_3y_pct                      1081593 non-null  float64
 120  ebitda_3y_pct                  1081593 non-null  float64
 121  opinc_3y_pct                   1081593 non-null  float64
 122  netinc_3y_pct                  1081593 non-null  float64
 123  eps_3y_pct                     1081593 non-null  float64
 124  assets_3y_pct                  1081593 non-null  float64
 125  ncfo_3y_pct                    1081593 non-null  float64
 126  ncf_3y_pct                     1081593 non-null  float64
 127  equity_3y_pct                  1081593 non-null  float64
 128  volume_change                  1081593 non-null  float64
 129  price_change                   1081593 non-null  float64
 130  price_change_sector            1081593 non-null  float64
 131  price_change_norm_sector       1081593 non-null  float64
 132  price_change_industry          1081593 non-null  float64
 133  price_change_norm_industry     1081593 non-null  float64
 134  price_weekly_avg               1081593 non-null  float64
 135  price_month_avg                1081593 non-null  float64
 136  price_quarter_avg              1081593 non-null  float64
 137  price_semi_annual_avg          1081593 non-null  float64
 138  price_annual_avg               1081593 non-null  float64
 139  price_two_year_avg             1081593 non-null  float64
 140  price_three_year_avg           1081593 non-null  float64
 141  volume_weekly_avg              1081593 non-null  float64
 142  volume_month_avg               1081593 non-null  float64
 143  volume_quarter_avg             1081593 non-null  float64
 144  volume_semi_annual_avg         1081593 non-null  float64
 145  volume_annual_avg              1081593 non-null  float64
 146  volume_two_year_avg            1081593 non-null  float64
 147  volume_three_year_avg          1081593 non-null  float64
 148  price_change_weekly_avg        1081593 non-null  float64
 149  price_change_month_avg         1081593 non-null  float64
 150  price_change_quarter_avg       1081593 non-null  float64
 151  price_change_semi_annual_avg   1081593 non-null  float64
 152  price_change_annual_avg        1081593 non-null  float64
 153  price_change_two_year_avg      1081593 non-null  float64
 154  price_change_three_year_avg    1081593 non-null  float64
 155  volume_change_weekly_avg       1081593 non-null  float64
 156  volume_change_month_avg        1081593 non-null  float64
 157  volume_change_quarter_avg      1081593 non-null  float64
 158  volume_change_semi_annual_avg  1081593 non-null  float64
 159  volume_change_annual_avg       1081593 non-null  float64
 160  volume_change_two_year_avg     1081593 non-null  float64
 161  volume_change_three_year_avg   1081593 non-null  float64
 162  divyield                       1081593 non-null  float64
 163  marketcap                      1081593 non-null  float64
 164  ev                             1081593 non-null  float64
 165  evebit                         1081593 non-null  float64
 166  pb                             1081593 non-null  float64
 167  pe                             1081593 non-null  float64
 168  peg1                           1081593 non-null  float64
 169  peg2                           1081593 non-null  float64
 170  peg3                           1081593 non-null  float64
 171  rating_cnt_strong_buys         1081593 non-null  float64
 172  rating_cnt_mod_buys            1081593 non-null  float64
 173  rating_cnt_holds               1081593 non-null  float64
 174  rating_cnt_mod_sells           1081593 non-null  float64
 175  rating_cnt_strong_sells        1081593 non-null  float64
 176  rating_mean_recom              1081593 non-null  float64
 177  rating_cnt_with                1081593 non-null  float64
 178  rating_cnt_without             1081593 non-null  float64
 179  rating_change                  1081593 non-null  int64
 180  dcf                            1081593 non-null  float64
 181  actualEarningResult            1081593 non-null  float64
 182  estimatedEarning               1081593 non-null  float64
 183  earnings_surprise              1081593 non-null  float64
dtypes: datetime64[ns](1), float64(174), int64(1), object(8)
memory usage: 1.5+ GB

In [38]:
final_df.to_pickle("final_df.pkl")

In [57]:
final_df.to_csv("final_df.csv")

### Export List of Final Tickers for Streamlit App

In [23]:
ticker_name = final_df[["ticker", "name"]]
ticker_name["tick_name"] = ticker_name.ticker + " - " + ticker_name.name

<ipython-input-23-abf20c7493c4>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ticker_name["tick_name"] = ticker_name.ticker + " - " + ticker_name.name

In [24]:
ticker_name

        ticker                      name                     tick_name
0            A  Agilent Technologies Inc  A - Agilent Technologies Inc
1            A  Agilent Technologies Inc  A - Agilent Technologies Inc
2            A  Agilent Technologies Inc  A - Agilent Technologies Inc
3            A  Agilent Technologies Inc  A - Agilent Technologies Inc
4            A  Agilent Technologies Inc  A - Agilent Technologies Inc
...        ...                       ...                           ...
1081588   ZYXI                 Zynex Inc              ZYXI - Zynex Inc
1081589   ZYXI                 Zynex Inc              ZYXI - Zynex Inc
1081590   ZYXI                 Zynex Inc              ZYXI - Zynex Inc
1081591   ZYXI                 Zynex Inc              ZYXI - Zynex Inc
1081592   ZYXI                 Zynex Inc              ZYXI - Zynex Inc

[1081593 rows x 3 columns]

In [25]:
final_tickers = list(ticker_name.tick_name.unique())

In [26]:
with open('final_tickers.pkl', 'wb') as handle:
    pickle.dump(final_tickers, handle, protocol=pickle.HIGHEST_PROTOCOL)